import axios from 'axios';
import * as XLSX from 'xlsx';
import { baseTimeOut } from '../configs/baseTimeOut';
export const useProcessData = async (data, hierarchyType, type, tenantId, id, baseTimeOut, additionalDetails = {}) => {
    let Error = {
        isError: false,
        error: {},
    };
    let response;
    const locale = Digit?.SessionStorage?.get("locale") || Digit?.SessionStorage.get("initData")?.selectedLanguage || Digit?.Utils?.getDefaultLanguage();
    const user = Digit.UserService.getUser();
    const userInfo = user?.info || user?.userInfo || {};
    const requestInfo = {
        apiId: "Rainmaker",
        authToken: user?.access_token,
        msgId: `${Date.now()}|${locale}`,
        userInfo,
        plainAccessRequest: {},
    };
    try {
        // Register/attendee templates are generated by excel-ingestion, so they must be validated there too.
        // Bulk mapping (attendanceRegisterUserBulkMapping) is project-factory generated and stays on project-factory.
        const isUnifiedConsole = type === "unified-console-validation";
        const isAttendanceRegister = type === "attendanceRegister-validation" || type === "attendanceRegisterAttendee-validation";
        const useExcelIngestion = isUnifiedConsole || isAttendanceRegister;
        const resourceDetails = {
            type,
            hierarchyType: hierarchyType,
            tenantId: Digit.ULBService.getCurrentTenantId(),
            fileStoreId: data?.[0]?.filestoreId,
            additionalDetails: additionalDetails,
        };

        if (useExcelIngestion) { //TODO CHECK
            resourceDetails.locale = locale;
            if (type === "attendanceRegisterAttendee-validation") {
                resourceDetails.type = "attendanceRegisterAttendee-validation";
                const campaignId = additionalDetails?.campaignId;
                const registerId = additionalDetails?.registerId;
                const isCampaignScopedValidation = !!campaignId && id === campaignId;

                if (isCampaignScopedValidation) {
                    resourceDetails.referenceId = campaignId;
                    resourceDetails.referenceType = "campaign";
                } else {
                    resourceDetails.referenceId = registerId || id;
                    resourceDetails.referenceType = "attendanceRegister";
                }
            } else if (type === "attendanceRegister-validation") {
                resourceDetails.type = "attendanceRegister-validation";
                resourceDetails.referenceId = id;
                resourceDetails.referenceType = "campaign";
            } else {
                resourceDetails.referenceId = id;
                resourceDetails.referenceType = "campaign";
            }
        } else {
            resourceDetails.campaignId = id;
        }

        const apiUrl = useExcelIngestion
            ? "/excel-ingestion/v1/data/process/_validation"
            : "/project-factory/v2/data/_process";

        const responseTemp = await Digit.CustomService.getResponse({
            url: apiUrl,
            body: {
                RequestInfo: requestInfo,
                ResourceDetails: resourceDetails,
            },
        });
        response = responseTemp;

    } catch (error) {
        if (error?.response && error?.response?.data) {
            const errorMessage = error?.response?.data?.Errors?.[0]?.message;
            const errorDescription = error?.response?.data?.Errors?.[0]?.description;
            if (errorDescription) {
                Error.error = `${errorMessage} : ${errorDescription}`;
                Error.isError = true;
                return Error;
            } else {
                Error = { error: String(error.message) };
                Error.isError = true;
                return Error;
            }
        }
    }

    let searchResponse;
    let status = "inprogress";
    const baseDelay = baseTimeOut?.baseTimeout?.[0]?.baseTimeOut;
    const maxTime = baseTimeOut?.baseTimeout?.[0]?.maxTime;
    let retryInterval = 2000;

    // Poll the same service the upload went to; bulk mapping stays on project-factory resource-details search.
    const isUnifiedConsole = type === "unified-console-validation";
    const isAttendanceRegister = type === "attendanceRegister-validation" || type === "attendanceRegisterAttendee-validation";
    const useExcelIngestion = isUnifiedConsole || isAttendanceRegister;
    const searchUrl = useExcelIngestion
        ? "/excel-ingestion/v1/data/process/_search"
        : "/project-factory/v1/resource-details/_search";

    // Get the ID from the response - different field for excel-ingestion 
    const processId = useExcelIngestion
        ? response?.ProcessResource?.id
        : response?.ResourceDetails?.id;

    await new Promise((resolve) => setTimeout(resolve, retryInterval));

    // Retry until a terminal status is received.
    // Project-factory bulk flow can return creating/toCreate while processing.
    const inProgressStatuses = ["inprogress", "pending", "creating", "toCreate", "created", "processing"];
    const isStatusPending = (s) => inProgressStatuses.includes(s);

    while (isStatusPending(status)) {
        try {
            if (useExcelIngestion) {
                searchResponse = await Digit.CustomService.getResponse({
                    url: searchUrl,
                    body: {
                        ProcessingSearchCriteria: {
                            tenantId: tenantId,
                            ids: [processId],
                            limit: 5,
                            offset: 0,
                        },
                        RequestInfo: requestInfo,
                    },
                });
                status = searchResponse?.ProcessingDetails?.[0]?.status;
            } else {
                searchResponse = await Digit.CustomService.getResponse({
                    url: searchUrl,
                    body: {
                        RequestInfo: requestInfo,
                        ResourceDetailsCriteria: {
                            ids: [processId],
                            tenantId: tenantId,
                            campaignId: additionalDetails?.campaignId || id,
                        },
                        Pagination: { limit: 5, offset: 0 },
                    },
                });
                status = searchResponse?.ResourceDetails?.[0]?.status;
            }

            if (isStatusPending(status)) {
                await new Promise((resolve) => setTimeout(resolve, retryInterval));
            }
            else if(!status){
                status = "inprogress";
                await new Promise((resolve) => setTimeout(resolve, retryInterval));
            }
        } catch (error) {
            console.error("Error while fetching data:", error);
        }
    }
    if (Error.isError) {
        return Error;
    }
    return useExcelIngestion
        ? searchResponse?.ProcessingDetails?.[0]
        : searchResponse?.ResourceDetails?.[0];
};