const { createProxyMiddleware } = require("http-proxy-middleware");

const createProxy = createProxyMiddleware({
  //target: process.env.REACT_APP_PROXY_API || "https://uat.digit.org",
  // target: process.env.REACT_APP_PROXY_API || "https://qa.digit.org",
  target: process.env.REACT_APP_PROXY_API || "https://works-dev.digit.org",
  changeOrigin: true,
  secure: false,
});
const assetsProxy = createProxyMiddleware({
  target: process.env.REACT_APP_PROXY_ASSETS || "https://works-dev.digit.org",
  changeOrigin: true,
  secure: false,
});
const mdmsProxy = createProxyMiddleware({
  target: process.env.REACT_APP_PROXY_ASSETS || "http://localhost:8080",
  changeOrigin: true,
  secure: false,
});
module.exports = function (app) {
  ["/mdms-v2/v2/_create"].forEach((location) => app.use(location, mdmsProxy));
  [
    "/access/v1/actions/mdms",
    "/egov-mdms-service",
    "/mdms-v2",
    "/egov-idgen",
    "/egov-location",
    "/localization",
    "/egov-workflow-v2",
    "/pgr-services",
    "/health-pgr-services",
    "/filestore",
    "/egov-hrms",
    "/user-otp",
    "/user",
    "/fsm",
    "/billing-service",
    "/collection-services",
    "/pdf-service",
    "/pg-service",
    "/vehicle",
    "/vendor",
    "/property-services",
    "/fsm-calculator/v1/billingSlab/_search",
    "/pt-calculator-v2",
    "/dashboard-analytics",
    "/echallan-services",
    "/egov-searcher/bill-genie/mcollectbills/_get",
    "/egov-searcher/bill-genie/billswithaddranduser/_get",
    "/egov-searcher/bill-genie/waterbills/_get",
    "/egov-searcher/bill-genie/seweragebills/_get",
    "/egov-pdf/download/UC/mcollect-challan",
    "/egov-hrms/employees/_count",
    "/tl-services/v1/_create",
    "/tl-services/v1/_search",
    "/egov-url-shortening/shortener",
    "/inbox/v1/_search",
    "/inbox/v2/_search",
    "/tl-services",
    "/tl-calculator",
    "/org-services",
    "/edcr",
    "/bpa-services",
    "/noc-services",
    "/egov-user-event",
    "/egov-document-uploader",
    "/egov-pdf",
    "/egov-survey-services",
    "/ws-services",
    "/sw-services",
    "/ws-calculator",
    "/sw-calculator/",
    "/egov-searcher",
    "/report",
    "/inbox/v1/dss/_search",
    "/loi-service",
    "/project/v1/",
    "/estimate-service",
    "/loi-service",
    "/works-inbox-service/v2/_search",
    "/egov-pdf/download/WORKSESTIMATE/estimatepdf",
    "/muster-roll",
    "/individual",
    "/mdms-v2",
    "/hcm-moz-impl",
    "/project",
    "/project/staff/v1/_search",
    "/project/v1/_search",
    "/facility/v1/_search",
    "/product/v1/_search",
    "/product/variant/v1/_search",
    "/hcm-bff/bulk/_transform",
    "/hcm-bff/hcm/_processmicroplan",
    "/health-hrms",
    "/project-factory",
    "/boundary-service",
    "/product",
    "/plan-service",
    "/resource-generator",
    "/health-project",
    "/service-request",
    "/health-service-request",
    "/census-service",
    "/health-attendance/v1/_search",
    "/health-individual/v1/_search",
    "/health-muster-roll",
    "/health-expense/bill/v1/_search",
    "/health-expense-calculator/v1/_calculate",
    "/filestore/v1/files/id",
    "/attendance/v1/_search",
    "/health-project/staff/v1/_search",
    "/project/staff/v1/_search",
    "/health-project/v1/_search",
    "/health-individual",
    "/health-hrms/employees",
    "/inbox/v2/_search",
    // attendee delete
    "/health-attendance/attendee/v1/_delete",
    "/health-attendance/attendee/v1/_create",
    "/health-hrms/employees/_search",
    //payment integration changes
    "/health-expense/bill/v1/_update",
    "/health-expense/v1/bill/details/status/_update",
    "/health-expense/v1/task/_status",
    "/health-expense/v1/bill/_verify",
    "/health-expense/v1/payment/_transfer",
    "/health-expense/v1/transactions/report/_search",
    "/health-expense/v1/transactions/report/_generate",
    // payment v2
    "/health-expense-calculator/billing-config/v1/_search",
    "/health-expense-calculator/billing-config/v1/_create",
    "/health-expense-calculator/billing-config/v1/_update"
  ].forEach((location) => app.use(location, createProxy));
  ["/pb-egov-assets"].forEach((location) => app.use(location, assetsProxy));
  ["/mdms-v2/v2/_create"].forEach((location) => app.use(location, mdmsProxy));
};
