export const LOCALE = {
  MY_COMPLAINTS: "CS_HOME_MY_COMPLAINTS",
  NO_COMPLAINTS: "CS_MYCOMPLAINTS_NO_COMPLAINTS",
  FILE_COMPLAINT: "CS_COMMON_FILE_A_COMPLAINT",
  HOME_COMPLAINTS: "CS_COMMON_HOME_COMPLAINTS",
};

export const LOCALIZATION_KEY = {
  CS_COMPLAINT_DETAILS: "CS_COMPLAINT_DETAILS",
  CS_COMMON: "CS_COMMON",
  ES_COMMON: "ES_COMMON",
  PGR: "PGR",
};
