/**
 * Command: digit-loc push --file <path> --env <url>
 *
 * Upserts a localization payload JSON file to a DIGIT environment.
 * The payload should be an array of { code, message, module, locale } objects,
 * typically generated by the `generate` command.
 *
 * Usage:
 *   digit-loc push --file payload.json --env https://uat.digit.org
 *   digit-loc push --file payload.json --env https://uat.digit.org --tenant bednet
 */

"use strict";

const fs = require("fs");
const path = require("path");
const { createClient } = require("../utils/digit-client");

module.exports = async function push({ positional, flags }) {
  const filePath = flags.file;
  const envUrl = flags.env;

  if (!filePath || !envUrl) {
    console.error("Usage: digit-loc push --file <path> --env <url>");
    console.error("  Upserts a localization payload to a DIGIT environment.");
    console.error("");
    console.error("Options:");
    console.error("  --file <path>    Path to payload JSON file (required)");
    console.error("  --env <url>      DIGIT environment base URL (required)");
    console.error("  --tenant <id>    Tenant ID (default: default)");
    console.error("  --token <token>  Auth token (or set DIGIT_AUTH_TOKEN env var)");
    console.error("  --dry-run        Show what would be pushed without pushing");
    process.exit(1);
  }

  const resolvedFile = path.resolve(filePath);

  if (!fs.existsSync(resolvedFile)) {
    console.error(`File not found: ${resolvedFile}`);
    process.exit(1);
  }

  let payload;
  try {
    const content = fs.readFileSync(resolvedFile, "utf-8");
    payload = JSON.parse(content);
  } catch (err) {
    console.error(`Failed to parse payload file: ${err.message}`);
    process.exit(1);
  }

  if (!Array.isArray(payload)) {
    console.error("Payload must be a JSON array of { code, message, module, locale } objects.");
    process.exit(1);
  }

  // Validate payload entries
  const validEntries = [];
  const invalidEntries = [];

  for (let i = 0; i < payload.length; i++) {
    const entry = payload[i];
    if (!entry.code || !entry.message) {
      invalidEntries.push({ index: i, reason: "missing code or message", entry });
    } else {
      validEntries.push(entry);
    }
  }

  if (invalidEntries.length > 0) {
    console.warn(`${invalidEntries.length} invalid entries will be skipped:`);
    for (const inv of invalidEntries.slice(0, 5)) {
      console.warn(`  [${inv.index}]: ${inv.reason}`);
    }
    if (invalidEntries.length > 5) {
      console.warn(`  ... and ${invalidEntries.length - 5} more`);
    }
    console.log("");
  }

  console.log(`Payload: ${validEntries.length} valid message(s) from ${resolvedFile}`);
  console.log(`Target: ${envUrl}`);

  // Group by module
  const byModule = new Map();
  for (const entry of validEntries) {
    const mod = entry.module || "default";
    if (!byModule.has(mod)) byModule.set(mod, []);
    byModule.get(mod).push(entry);
  }

  console.log(`Modules: ${Array.from(byModule.keys()).join(", ")}`);
  console.log("");

  if (flags["dry-run"]) {
    console.log("DRY RUN — would push the following:");
    for (const [mod, entries] of byModule) {
      console.log(`\n  Module: ${mod} (${entries.length} messages)`);
      for (const e of entries.slice(0, 10)) {
        console.log(`    ${e.code}: "${e.message}"`);
      }
      if (entries.length > 10) {
        console.log(`    ... and ${entries.length - 10} more`);
      }
    }
    return;
  }

  // Check for auth token
  const token = flags.token || process.env.DIGIT_AUTH_TOKEN;
  if (!token) {
    console.error("Auth token required for push. Set --token or DIGIT_AUTH_TOKEN env var.");
    process.exit(1);
  }

  const client = createClient({
    envUrl,
    token,
    tenant: flags.tenant,
  });

  // Push each module's messages
  let totalPushed = 0;

  for (const [mod, entries] of byModule) {
    console.log(`Pushing ${entries.length} message(s) to module "${mod}"...`);

    try {
      await client.upsertMessages(entries);
      totalPushed += entries.length;
      console.log(`  Done.`);
    } catch (err) {
      console.error(`  Failed: ${err.message}`);
    }
  }

  console.log("");
  console.log(`Pushed ${totalPushed}/${validEntries.length} message(s) to ${envUrl}.`);
};
