export const BoundaryTypes = Object.freeze({
    NATIONAL: "COUNTRY",
    PROVINCE: "PROVINCE",
    DISTRICT: "DISTRICT",
    ADMINISTRATIVE_PROVINCE: "ADMINISTRATIVEPOST",
    LOCALITY: "LOCALITY",
    VILLAGE: "VILLAGE"
});

 

export const ReposeScreenType = Object.freeze({
    CREAT_EUSER: "CREATEUSER",
    EDIT_USER: "EDITUSER",
    CREATE_USER_ERROR: "CREATEUSERERROR",
    EDIT_USER_ERROR: "EDITUSERERROR",
    ASSIGN_CAMPAIGN: "ASSIGNCAMPAIGN",
    EDIT_ASSIGNED_CAMPAIGN: "EDITASSIGNEDCAMPAIGN",
    EDIT_ASSIGNED_CAMPAIGN_ERROR: "EDITASSIGNEDCAMPAIGNERROR"
});


