#!/bin/sh

# Get the current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Define the pattern
PATTERN="^(FEATURE|BUGFIX|RELEASE)\/(HCMPRE|DPG|SN)-[0-9]{1,5}$"

# Check if the branch name matches the pattern
if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
  echo "Branch name '$BRANCH_NAME' does not follow the correct pattern:"
  echo " - FEATURE/HCMPRE-<TICKET_NO>"
  echo " - FEATURE/DPG-<TICKET_NO>"
  echo " - FEATURE/SN-<TICKET_NO>"
  echo " - BUGFIX/HCMPRE-<TICKET_NO>"
  echo " - BUGFIX/DPG-<TICKET_NO>"
  echo " - BUGFIX/SN-<TICKET_NO>"
  echo " - RELEASE/HCMPRE-<TICKET_NO>"
  echo " - RELEASE/DPG-<TICKET_NO>"
  echo "Where <TICKET_NO> is a number between 0 and 99999."
  exit 1
fi

# If the pattern matches, allow the push
exit 0
