name: Fuzz Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run fuzz tests
        run: npm run test:fuzz
