import { Card, Header, Label, UploadFile } from "@egovernments/digit-ui-react-components";
import React, { useState } from "react";
// Removed @cyntler/react-doc-viewer to fix CVE-2024-4367 (pdfjs-dist vulnerability).
// Replaced with Office Online iframe for document preview.

const SUPPORTED_FILE_FORMATS = [
  ".pdf",
  ".bmp",
  ".xlsx",
  ".csv",
  ".doc",
  ".docx",
  ".gif",
  ".htm",
  ".html",
  ".jpg",
  ".jpeg",
  ".png",
  ".ppt",
  ".pptx",
  ".tiff",
  ".txt",
  ".xls",
];

const OFFICE_PREVIEWABLE = [".xlsx", ".xls", ".doc", ".docx", ".ppt", ".pptx", ".csv"];
const IMAGE_TYPES = [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff"];

const sanitizeUri = (value) => {
  if (!value) return null;
  // Allow blob: URLs generated by createObjectURL without further parsing.
  if (typeof value === "string" && value.startsWith("blob:")) return value;
  try {
    // Allow HTTP(S) and blob/data URLs typically produced by createObjectURL
    const parsed = new URL(value, window.location.origin);
    const allowedSchemes = ["http:", "https:", "blob:"];
    if (!allowedSchemes.includes(parsed.protocol)) {
      return null;
    }
    return parsed.href;
  } catch (e) {
    // If URL constructor throws, treat as unsafe
    return null;
  }
};

const getPreviewContent = (uri, fileName) => {
  const safeUri = sanitizeUri(uri);
  if (!safeUri) {
    return <span>Unable to preview this file.</span>;
  }
  const ext = fileName ? `.${fileName.split(".").pop().toLowerCase()}` : "";
  if (OFFICE_PREVIEWABLE.includes(ext)) {
    return (
      <iframe
        src={`https://view.officeapps.live.com/op/embed.aspx?src=${encodeURIComponent(safeUri)}`}
        style={{ width: "100%", height: "80vh", border: "none" }}
        title="Document Preview"
      />
    );
  }
  if (ext === ".pdf") {
    return (
      <iframe
        src={safeUri}
        style={{ width: "100%", height: "80vh", border: "none" }}
        title="PDF Preview"
      />
    );
  }
  if (IMAGE_TYPES.includes(ext)) {
    return <img src={safeUri} alt={fileName} style={{ maxWidth: "100%", maxHeight: "80vh" }} />;
  }
  if (ext === ".txt" || ext === ".htm" || ext === ".html") {
    return (
      <iframe
        src={safeUri}
        sandbox=""
        style={{ width: "100%", height: "80vh", border: "none" }}
        title="Text Preview"
      />
    );
  }
  return <a href={safeUri} download={fileName}>Download {fileName}</a>;
};

const DocViewerWrapper = (props) => {
  const { fileUrl, fileName = "Unknown File" } = Digit.Hooks.useQueryParams();

  const [selectedDocs, setSelectedDocs] = useState([]);
  const documents = fileUrl
    ? [{ uri: fileUrl, fileName }]
    : selectedDocs.map((file) => ({
        uri: window.URL.createObjectURL(file),
        fileName: file?.name || fileName,
      }));

  return (
    <Card>
      <Header>File Viewer</Header>
      {!fileUrl && (
        <UploadFile
          accept={SUPPORTED_FILE_FORMATS.join(",")}
          multiple
          uploadedFiles={selectedDocs}
          enableButton={true}
          removeTargetedFile={(file) => setSelectedDocs([])}
          showHintBelow={true}
          hintText={`Supported File Formats : ${SUPPORTED_FILE_FORMATS.join(", ")} `}
          onUpload={(el) => el.target.files?.length && setSelectedDocs(Array.from(el.target.files))}
        />
      )}
      {documents?.length != 0 && (
        <>
          <Label>Uploaded File</Label>
          {documents.map((doc, idx) => (
            <div key={idx} style={{ marginBottom: "1rem" }}>
              {getPreviewContent(doc.uri, doc.fileName)}
            </div>
          ))}
        </>
      )}
    </Card>
  );
};

export default DocViewerWrapper;

// const docs = [
//     { uri: "https://url-to-my-pdf.pdf" }, // Remote file
//     { uri: require("./example-files/pdf.pdf") }, // Local File
//   ];

//   return (
//     <DocViewer
//       documents={docs}
//       initialActiveDocument={docs[1]}
//       pluginRenderers={DocViewerRenderers}
//     />
//   );

// theme={{
//     primary: "#5296d8",
//     secondary: "#ffffff",
//     tertiary: "#5296d899",
//     textPrimary: "#ffffff",
//     textSecondary: "#5296d8",
//     textTertiary: "#00000099",
//     disableThemeScrollbar: false,
//   }}

// Custom Request Headers
// Provide request headers, i.e. for authenticating with an API etc.

// const headers = {
//   "X-Access-Token": "1234567890",
//   "My-Custom-Header": "my-custom-value",
// };

// <DocViewer documents={docs} prefetchMethod="GET" requestHeaders={headers} />;

// Internationalization (i18n)
// From v1.6.0 you can pass the language prop to the DocViewer component to get translated sentences and words that can be displayed by this library.

// <DocViewer documents={docs} language="pl" />

// Styling
// Any styling applied to the <DocViewer> component, is directly applied to the main div container.

// CSS Class
// <DocViewer documents={docs} className="my-doc-viewer-style" />
// CSS Class Default Override
// Each component / div already has a DOM id that can be used to style any part of the document viewer.

// #react-doc-viewer #header-bar {
//   background-color: #faf;
// }
// React Inline
// <DocViewer documents={docs} style={{ width: 500, height: 500 }} />

// refer more here
// https://www.npmjs.com/package/@cyntler/react-doc-viewer/v/1.10.3#config

// bmp	image/bmp
// csv	text/csv
// doc	application/msword
// docx	application/vnd.openxmlformats-officedocument.wordprocessingml.document
// gif	image/gif
// htm	text/htm
// html	text/html
// jpg	image/jpg
// jpeg	image/jpeg
// pdf	application/pdf
// png	image/png
// ppt	application/vnd.ms-powerpoint
// pptx	applicatiapplication/vnd.openxmlformats-officedocument.presentationml.presentation
// tiff	image/tiff
// txt	text/plain
// xls	application/vnd.ms-excel
// xlsx
