version: '3.8'

services:
  web-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        WORK_DIR: ./
    ports:
      - "8080:80"      # Nginx serving React app
      - "3001:3001"    # Proxy server for Elasticsearch
    environment:
      - PROXY_PORT=3001
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://elasticsearch:9200}
      - KIBANA_URL=${KIBANA_URL:-http://kibana:5601}
    networks:
      - elastic-network
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./proxy:/usr/local/share/proxy-config:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

networks:
  elastic-network:
    driver: bridge

volumes:
  es-data:
    driver: local