const { merge } = require("webpack-merge");
const common = require("./webpack.common.js");
const webpack = require("webpack");
const path = require("path");

module.exports = merge(common, {
  mode: "development",
  devtool: "eval-source-map",

  output: {
    filename: "[name].bundle.js",
    chunkFilename: "[name].chunk.js",
    publicPath: "/digit-studio/",
  },

  devServer: {
    static: {
      directory: path.join(__dirname, "public"),
    },
    historyApiFallback: {
      index: "/digit-studio/index.html",
    },
    compress: true,
    port: process.env.PORT || 3000,
    hot: true,
    liveReload: false, // Disable auto refresh to prevent conflicts
    open: true,
    client: {
      overlay: {
        errors: true,
        warnings: false,
      },
      progress: true,
    },
    watchFiles: {
      paths: ["packages/**/*"],
      options: {
        usePolling: false,
        ignored: /node_modules/,
      },
    },
    proxy: [
      {
        context: [
          "/egov-mdms-service",
          "/access/v1/actions/mdms",
          "/tenant-management",
          "/user-otp",
          "/mdms-v2",
          "/egov-idgen",
          "/egov-location",
          "/localization",
          "/egov-workflow-v2",
          "/pgr-services",
          "/filestore",
          "/egov-hrms",
          "/user",
          "/fsm",
          "/billing-service",
          "/collection-services",
          "/pdf-service",
          "/pg-service",
          "/vehicle",
          "/vendor",
          "/property-services",
          "/dashboard-analytics",
          "/egov-searcher",
          "/egov-pdf",
          "/egov-url-shortening",
          "/inbox",
          "/report",
          "/loi-service",
          "/project",
          "/estimate-service",
          "/muster-roll",
          "/individual",
          "/facility",
          "/boundary-service",
          "/org-services",
          "/bpa-services",
          "/noc-services",
          "/health-hrms",
          "/health-project",
          "/fsm-calculator",
          "/product",
          "/health-service-request",
          "/excel-ingestion",
          "/boundary-management",
          "/access/v1/actions/mdms",
    "/egov-mdms-service",
    "/mdms-v2",
    "/egov-idgen",
    "/egov-location",
    "/boundary-service",
    "/localization",
    "/egov-workflow-v2",
    "/pgr-services",
    "/filestore",
    "/egov-hrms",
    "/user-otp",
    "/user",
    "/fsm",
    "/billing-service",
    "/collection-services",
    "/pdf-service",
    "/pg-service",
    "/vehicle",
    "/estimate",
    "/vendor",
    "/property-services",
    "/fsm-calculator/v1/billingSlab/_search",
    "/pt-calculator-v2",
    "/dashboard-analytics",
    "/echallan-services",
    "/egov-searcher/bill-genie/mcollectbills/_get",
    "/egov-searcher/bill-genie/billswithaddranduser/_get",
    "/egov-searcher/bill-genie/waterbills/_get",
    "/egov-searcher/bill-genie/seweragebills/_get",
    "/egov-pdf/download/UC/mcollect-challan",
    "/egov-hrms/employees/_count",
    "/tl-services/v1/_create",
    "/tl-services/v1/_search",
    "/egov-url-shortening/shortener",
    "/health-service-request",
    "/inbox/v1/_search",
    "/inbox/v2/_search",
    "/public-service",
    "/public-service-init",
    "/tl-services",
    "/tl-calculator",
    "/org-services",
    "/edcr",
    "/bpa-services",
    "/noc-services",
    "/egov-user-event",
    "/egov-document-uploader",
    "/egov-pdf",
    "/egov-survey-services",
    "/ws-services",
    "/sw-services",
    "/ws-calculator",
    "/sw-calculator/",
    "/egov-searcher",
    "/report",
    "/inbox/v1/dss/_search",
    "/loi-service",
    "/project/v1/",
    "/estimate-service",
    "/loi-service",
    "/works-inbox-service/v2/_search",
    "/egov-pdf/download/WORKSESTIMATE/estimatepdf",
    "/muster-roll",
    "/individual",
    "/mdms-v2",
    "/hcm-moz-impl",
    "/project",
    "/project/staff/v1/_search",
    "/project/v1/_search",
    "/facility/v1/_search",
    "/product/v1/_search",
    "/product/variant/v1/_search",
    "/hcm-bff/bulk/_transform",
    "/hcm-bff/hcm/_processmicroplan",
    "/health-hrms",
    "/mdms-v2/v1/_search",
    "/studio-pdf",
    "/health-individual"
        ],
        target: process.env.REACT_APP_PROXY_URL || "https://unified-uat.digit.org",
        changeOrigin: true,
        secure: false,
      },
    ],
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify("development"),
    }),
  ],

  optimization: {
    runtimeChunk: "single",
    splitChunks: {
      chunks: "all",
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: "vendors",
          priority: -10,
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true,
        },
      },
    },
  },

  performance: {
    hints: false,
  },
});
