// ============================================================================
// LOCALIZATION CONSTANTS - CAMPAIGN MANAGER MODULE
// ============================================================================
// This file contains all localization string constants used in the campaign-manager module.
// All t() translation function calls should reference constants from this file.
//
// IMPORTANT: When adding new localization strings, follow these steps:
// 1. Add the constant to the appropriate category below
// 2. Use the constant in your component: t(LOCALIZATION.YOUR_CONSTANT)
// 3. Ensure the actual translation exists in the localization service
//
// See README.md in this folder for detailed usage guidelines.
// ============================================================================

export const LOCALIZATION = {
  // ==========================================================================
  // 1. COMMONLY USED KEYS - Buttons, Actions, and Navigation
  // ==========================================================================
  // Basic Actions
  BACK: "BACK",
  CLOSE: "CLOSE",
  NEXT: "NEXT",
  SUBMIT: "SUBMIT",
  CANCEL: "CANCEL",
  UPDATE: "UPDATE",
  CREATE: "CREATE",
  SAVE: "SAVE",
  DELETE: "DELETE",
  EDIT: "EDIT",
  VIEW: "VIEW",
  DOWNLOAD: "DOWNLOAD",
  UPLOAD: "UPLOAD",
  SEARCH: "SEARCH",
  CLEAR: "CLEAR",
  CONFIRM: "CONFIRM",
  YES: "YES",
  NO: "NO",
  OK: "OK",
  PREVIEW: "PREVIEW",
  GO_BACK: "GO_BACK",
  ADD: "ADD",
  SELECT_ALL: "SELECT_ALL",
  CLEAR_ALL: "CLEAR_ALL",
  LOADING: "LOADING",
  RETRY: "RETRY",

  // Common HCM Actions
  HCM_BACK: "HCM_BACK",
  HCM_SUBMIT: "HCM_SUBMIT",
  HCM_NEXT: "HCM_NEXT",
  HCM_UPDATE: "HCM_UPDATE",
  HCM_CLEAR_ALL: "HCM_CLEAR_ALL",

  // Common Labels
  NA: "NA",
  ES_COMMON_NA: "ES_COMMON_NA",
  COMMON_BACK: "COMMON_BACK",
  ES_MORE: "ES_MORE",
  REQUIRED: "REQUIRED",
  DIGIT_SELECT: "DIGIT_SELECT",
  DIGIT_CLOSE: "DIGIT_CLOSE",
  DIGIT_CONFIRM_SELECTION: "DIGIT_CONFIRM_SELECTION",
  DIGIT_DEFAULT_MESSAGE: "DIGIT_DEFAULT_MESSAGE",

  // File Upload Actions
  WBH_DRAG_DROP: "WBH_DRAG_DROP",
  WBH_BULK_BROWSE_FILES: "WBH_BULK_BROWSE_FILES",

  // Workbench Actions
  WBH_DOWNLOAD: "WBH_DOWNLOAD",
  WBH_DELETE: "WBH_DELETE",
  WBH_DOWNLOAD_TEMPLATE: "WBH_DOWNLOAD_TEMPLATE",
  WBH_DOWNLOAD_XLS: "WBH_DOWNLOAD_XLS",

  // ==========================================================================
  // 2. TOAST MESSAGES - Success and Error Messages
  // ==========================================================================
  // Success Messages
  HCM_DRAFT_SUCCESS: "HCM_DRAFT_SUCCESS",
  ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE: "ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE",
  ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE_TEXT: "ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE_TEXT",
  ES_CAMPAIGN_SUCCESS_INFO_TEXT: "ES_CAMPAIGN_SUCCESS_INFO_TEXT",
  HCM_CAMPAIGN_SUCCESS_RESPONSE_ACTION: "HCM_CAMPAIGN_SUCCESS_RESPONSE_ACTION",
  ES_CHECKLIST_CREATE_SUCCESS_RESPONSE: "ES_CHECKLIST_CREATE_SUCCESS_RESPONSE",
  ES_CHECKLIST_CREATE_SUCCESS_RESPONSE_PRE_TEXT: "ES_CHECKLIST_CREATE_SUCCESS_RESPONSE_PRE_TEXT",
  ES_CHECKLIST_UPDATE_SUCCESS_RESPONSE: "ES_CHECKLIST_UPDATE_SUCCESS_RESPONSE",
  ES_CHECKLIST_UPDATE_SUCCESS_RESPONSE_PRE_TEXT: "ES_CHECKLIST_UPDATE_SUCCESS_RESPONSE_PRE_TEXT",
  ES_PRODUCT_CREATE_SUCCESS_RESPONSE: "ES_PRODUCT_CREATE_SUCCESS_RESPONSE",
  ES_PRODUCT_CREATE_SUCCESS_RESPONSE_PRE_TEXT: "ES_PRODUCT_CREATE_SUCCESS_RESPONSE_PRE_TEXT",
  ES_PRODUCT_CREATE_SUCCESS_RESPONSE_BOLD_TEXT: "ES_PRODUCT_CREATE_SUCCESS_RESPONSE_BOLD_TEXT",
  ES_PRODUCT_CREATE_SUCCESS_RESPONSE_POST_TEXT: "ES_PRODUCT_CREATE_SUCCESS_RESPONSE_POST_TEXT",
  ES_BOUNDARY_DATA_CREATED_SUCCESS_RESPONSE: "ES_BOUNDARY_DATA_CREATED_SUCCESS_RESPONSE",
  ES_BOUNDARY_DATA__CREATED_SUCCESS_RESPONSE_PRE_TEXT: "ES_BOUNDARY_DATA__CREATED_SUCCESS_RESPONSE_PRE_TEXT",
  FILE_UPLOADED_SUCCESSFULLY: "FILE_UPLOADED_SUCCESSFULLY",
  HCM_VALIDATION_COMPLETED: "HCM_VALIDATION_COMPLETED",
  CAMPAIGN_CREATED_SUCCESSFULLY: "CAMPAIGN_CREATED_SUCCESSFULLY",
  HIERARCHY_CREATED_SUCCESSFULLY: "HIERARCHY_CREATED_SUCCESSFULLY",
  TEMPLATE_GENERATED_SUCCESSFULLY: "TEMPLATE_GENERATED_SUCCESSFULLY",
  WBH_HIERARCHY_STATUS_COMPLETED: "WBH_HIERARCHY_STATUS_COMPLETED",
  CAMPAIGN_USER_GENERATION_SUCCESS: "CAMPAIGN_USER_GENERATION_SUCCESS",
  HCM_MAPPING_ADDED: "HCM_MAPPING_ADDED",
  DIGIT_LOC_UPSERT_SUCCESS: "DIGIT_LOC_UPSERT_SUCCESS",
  CMN_ALL_DATA_FETCH_DONE: "CMN_ALL_DATA_FETCH_DONE",
  ES_CAMPAIGN_DATE_CHANGE_WITH_BOUNDARY_SUCCESS: "ES_CAMPAIGN_DATE_CHANGE_WITH_BOUNDARY_SUCCESS",
  ES_CAMPAIGN_DATE_CHANGE_SUCCESS: "ES_CAMPAIGN_DATE_CHANGE_SUCCESS",

  // Error Messages
  HCM_ERROR: "HCM_ERROR",
  ERROR_CREATE_CAMPAIGN: "ERROR_CREATE_CAMPAIGN",
  HCM_ERROR_IN_CAMPAIGN_CREATION: "HCM_ERROR_IN_CAMPAIGN_CREATION",
  ES_CAMPAIGN_FAILED_ERROR: "ES_CAMPAIGN_FAILED_ERROR",
  HCM_ERROR_MORE_THAN_ONE_FILE: "HCM_ERROR_MORE_THAN_ONE_FILE",
  HCM_CONSOLE_ERROR_FILE_UPLOAD_FAILED: "HCM_CONSOLE_ERROR_FILE_UPLOAD_FAILED",
  HCM_CONSOLE_ERROR_FILE_FETCH_FAILED: "HCM_CONSOLE_ERROR_FILE_FETCH_FAILED",
  HCM_ERROR_FILE_UPLOAD: "HCM_ERROR_FILE_UPLOAD",
  HCM_FILE_UPLOAD_ERROR: "HCM_FILE_UPLOAD_ERROR",
  HCM_FILE_VALIDATION_ERROR: "HCM_FILE_VALIDATION_ERROR",
  HCM_ERROR_INVALID_FILE_TYPE: "HCM_ERROR_INVALID_FILE_TYPE",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  INVALID_GEOJSON_FILE: "INVALID_GEOJSON_FILE",
  ENTER_VALID_FILE: "ENTER_VALID_FILE",
  HCM_VALIDATION_FAILED: "HCM_VALIDATION_FAILED",
  SHOW_ERROR: "SHOW_ERROR",
  ERROR_FETCHING_CAMPAIGN: "ERROR_FETCHING_CAMPAIGN",
  ERROR_FETCHING_MICROPLAN: "ERROR_FETCHING_MICROPLAN",
  ERROR_WHILE_DOWNLOADING: "ERROR_WHILE_DOWNLOADING",
  ERROR_LOADING_BASE_MAP: "ERROR_LOADING_BASE_MAP",
  FAILED_TO_CREATE_COPY_CAMPAIGN: "FAILED_TO_CREATE_COPY_CAMPAIGN",
  HIERARCHY_CREATION_FAILED: "HIERARCHY_CREATION_FAILED",
  BOUNDARY_LOCALISATION_ERROR: "BOUNDARY_LOCALISATION_ERROR",
  LOCALIZATION_FAILED_PLEASE_TRY_AGAIN: "LOCALIZATION_FAILED_PLEASE_TRY_AGAIN",
  TEMPLATE_GENERATION_TIMEOUT: "TEMPLATE_GENERATION_TIMEOUT",
  TEMPLATE_GENERATION_FAILED: "TEMPLATE_GENERATION_FAILED",
  WBH_BOUNDARY_CREATION_TIMEOUT: "WBH_BOUNDARY_CREATION_TIMEOUT",
  WBH_OPERATION_INCOMPLETE: "WBH_OPERATION_INCOMPLETE",
  WBH_BOUNDARY_CREATION_FAIL: "WBH_BOUNDARY_CREATION_FAIL",
  APP_CONFIG_ERROR: "APP_CONFIG_ERROR",
  APP_CONFIG_ERROR_LOADING_CONFIGURATION: "APP_CONFIG_ERROR_LOADING_CONFIGURATION",
  APP_CONFIG_FAILED_TO_FETCH_FLOW_CONFIG: "APP_CONFIG_FAILED_TO_FETCH_FLOW_CONFIG",
  APP_CONFIG_FAILED_TO_FETCH_PAGE_CONFIG: "APP_CONFIG_FAILED_TO_FETCH_PAGE_CONFIG",
  APP_CONFIG_FAILED_TO_LOAD_FLOW_CONFIG: "APP_CONFIG_FAILED_TO_LOAD_FLOW_CONFIG",
  SOME_ERROR_OCCURED_IN_FETCH: "SOME_ERROR_OCCURED_IN_FETCH",
  SOME_ERROR_OCCURED_IN_FETCH_RETRYING: "SOME_ERROR_OCCURED_IN_FETCH_RETRYING",
  DIGIT_LOC_MODULE_DATA_LOAD_FAILED: "DIGIT_LOC_MODULE_DATA_LOAD_FAILED",
  DIGIT_LOC_UPLOAD_UNKNOWN_ERROR: "DIGIT_LOC_UPLOAD_UNKNOWN_ERROR",
  DIGIT_LOC_EMPTY_OR_INVALID_FILE: "DIGIT_LOC_EMPTY_OR_INVALID_FILE",
  DIGIT_LOC_INVALID_FILE: "DIGIT_LOC_INVALID_FILE",
  DIGIT_LOC_NO_VALID_ENTRIES: "DIGIT_LOC_NO_VALID_ENTRIES",
  DIGIT_LOC_PARSER_NOT_AVAILABLE: "DIGIT_LOC_PARSER_NOT_AVAILABLE",
  DIGIT_LOC_SELECT_MODULE_FIRST: "DIGIT_LOC_SELECT_MODULE_FIRST",

  // Warning/Progress Messages
  PLEASE_WAIT_WHILE_UPDATING: "PLEASE_WAIT_WHILE_UPDATING",
  HCM_PLEASE_WAIT: "HCM_PLEASE_WAIT",
  HCM_PLEASE_WAIT_TRY_IN_SOME_TIME: "HCM_PLEASE_WAIT_TRY_IN_SOME_TIME",
  CAMPAIGN_CREATION_TAKES_SOME_TIME_PLEASE_WAIT: "CAMPAIGN_CREATION_TAKES_SOME_TIME_PLEASE_WAIT",
  HCM_CAMPAIGN_CREATION_PROGRESS: "HCM_CAMPAIGN_CREATION_PROGRESS",
  ES_CAMPAIGN_CREATING: "ES_CAMPAIGN_CREATING",
  ES_CAMPAIGN_RETRY: "ES_CAMPAIGN_RETRY",
  RETRY_IN_PROGRESS: "RETRY_IN_PROGRESS",
  HCM_FILE_VALIDATION_PROGRESS: "HCM_FILE_VALIDATION_PROGRESS",
  HCM_FILE_VALIDATION: "HCM_FILE_VALIDATION",
  CAMPAIGN_VALIDATION_INPROGRESS: "CAMPAIGN_VALIDATION_INPROGRESS",
  VALIDATING_CAMPAIGN_NAME: "VALIDATING_CAMPAIGN_NAME",
  CREATING_CAMPAIGN_COPY: "CREATING_CAMPAIGN_COPY",
  FETCHING_MICROPLAN_DATA: "FETCHING_MICROPLAN_DATA",
  TEMPLATE_GENERATION_IN_PROGRESS: "TEMPLATE_GENERATION_IN_PROGRESS",
  HIERARCHY_PLEASE_WAIT: "HIERARCHY_PLEASE_WAIT",
  LOADING_MODULE: "LOADING_MODULE",
  PLS_WAIT_UNTIL_PAGE_REDIRECTS: "PLS_WAIT_UNTIL_PAGE_REDIRECTS",
  EMPTY_TEMPLATE_GENERTAION_NOTCOMPLETED_STILL_PROCEEDING: "EMPTY_TEMPLATE_GENERTAION_NOTCOMPLETED_STILL_PROCEEDING",

  // ==========================================================================
  // 3. CREATE CAMPAIGN FLOW
  // ==========================================================================
  // Campaign Home & Navigation
  ES_CAMPAIGN_HOME: "ES_CAMPAIGN_HOME",
  CAMPAIGN_HOME: "CAMPAIGN_HOME",
  CREATE_CAMPAIGN_HOME: "CREATE_CAMPAIGN_HOME",
  CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
  CREATE_NEW_CAMPAIGN: "CREATE_NEW_CAMPAIGN",
  ACTION_TEST_CREATE_CAMPAIGN: "ACTION_TEST_CREATE_CAMPAIGN",
  ACTION_TEST_CAMPAIGN: "ACTION_TEST_CAMPAIGN",
  HCM_CREATE_CAMPAIGN: "HCM_CREATE_CAMPAIGN",
  BACK_TO_MODULES: "BACK_TO_MODULES",

  // Campaign Details
  HCM_CAMPAIGN_DETAILS: "HCM_CAMPAIGN_DETAILS",
  CAMPAIGN_DETAILS: "CAMPAIGN_DETAILS",
  HCM_VIEW_DETAILS_DESCRIPTION: "HCM_VIEW_DETAILS_DESCRIPTION",
  VIEW_DETAILS: "VIEW_DETAILS",

  // Campaign Type Selection
  HCM_CAMPAIGN_TYPE: "HCM_CAMPAIGN_TYPE",
  HCM_CAMPAIGN_TYPE_HEADER: "HCM_CAMPAIGN_TYPE_HEADER",
  HCM_CAMPAIGN_TYPE_DESCRIPTION: "HCM_CAMPAIGN_TYPE_DESCRIPTION",
  HCM_BENEFICIARY_TYPE: "HCM_BENEFICIARY_TYPE",
  HCM_UPDATE_CAMPAIGN_TYPE_INFO: "HCM_UPDATE_CAMPAIGN_TYPE_INFO",
  ES_CAMPAIGN_UPDATE_TYPE_MODAL_HEADER: "ES_CAMPAIGN_UPDATE_TYPE_MODAL_HEADER",
  ES_CAMPAIGN_UPDATE_TYPE_MODAL_TEXT: "ES_CAMPAIGN_UPDATE_TYPE_MODAL_TEXT",
  ES_CAMPAIGN_BOUNDARY_MODAL_BACK: "ES_CAMPAIGN_BOUNDARY_MODAL_BACK",
  ES_CAMPAIGN_BOUNDARY_MODAL_SUBMIT: "ES_CAMPAIGN_BOUNDARY_MODAL_SUBMIT",

  // Campaign Name
  HCM_CAMPAIGN_NAME_HEADER: "HCM_CAMPAIGN_NAME_HEADER",
  HCM_CAMPAIGN_NAME_DESCRIPTION: "HCM_CAMPAIGN_NAME_DESCRIPTION",
  HCM_CAMPAIGN_NAME: "HCM_CAMPAIGN_NAME",
  HCM_CAMPAIGN_NAME_EXAMPLE: "HCM_CAMPAIGN_NAME_EXAMPLE",
  HCM_CAMPAIGN_NAME_DETAILS: "HCM_CAMPAIGN_NAME_DETAILS",
  CONSOLE_NAMING_CONVENTION: "CONSOLE_NAMING_CONVENTION",
  CAMPAIGN_NAME_ALREADY_EXIST: "CAMPAIGN_NAME_ALREADY_EXIST",
  CAMPAIGN_FIELD_ERROR_MANDATORY: "CAMPAIGN_FIELD_ERROR_MANDATORY",
  CAMPAIGN_NAME_GREATER: "CAMPAIGN_NAME_GREATER",
  ES__REQUIRED_NAME_AND_LENGTH: "ES__REQUIRED_NAME_AND_LENGTH",
  MAX_LENGTH_60: "MAX_LENGTH_60",

  // Campaign Dates
  HCM_CAMPAIGN_DATE: "HCM_CAMPAIGN_DATE",
  HCM_CAMPAIGN_DATES: "HCM_CAMPAIGN_DATES",
  HCM_CAMPAIGN_DATES_HEADER: "HCM_CAMPAIGN_DATES_HEADER",
  HCM_CAMPAIGN_DATES_DESC: "HCM_CAMPAIGN_DATES_DESC",
  HCM_CAMPAIGN_DATES_DESCRIPTION: "HCM_CAMPAIGN_DATES_DESCRIPTION",
  HCM_START_DATE: "HCM_START_DATE",
  HCM_END_DATE: "HCM_END_DATE",
  START_DATE: "START_DATE",
  END_DATE: "END_DATE",
  START_DATE_LABEL: "Start Date",
  END_DATE_LABEL: "End Date",
  START_DATE_KEY: "startDate",
  END_DATE_KEY: "endDate",
  CAMPAIGN_START_DATE: "CAMPAIGN_START_DATE",
  CAMPAIGN_END_DATE: "CAMPAIGN_END_DATE",
  FROM_DATE: "FROM_DATE",
  TO_DATE: "TO_DATE",
  DURATION: "DURATION",
  Days: "Days",

  // Date Validation Errors
  CAMPAIGN_FIELD_MANDATORY: "CAMPAIGN_FIELD_MANDATORY",
  CAMPAIGN_START_DATE_ERROR: "CAMPAIGN_START_DATE_ERROR",
  CAMPAIGN_END_DATE_ERROR: "CAMPAIGN_END_DATE_ERROR",
  CAMPAIGN_END_DATE_SAME_ERROR: "CAMPAIGN_END_DATE_SAME_ERROR",
  CAMPAIGN_END_DATE_BEFORE_ERROR: "CAMPAIGN_END_DATE_BEFORE_ERROR",
  INVALID_DATES: "INVALID_DATES",

  // Cycle Configuration
  CAMPAIGN_NO_OF_CYCLE: "CAMPAIGN_NO_OF_CYCLE",
  CAMPAIGN_NO_OF_CYCLES: "CAMPAIGN_NO_OF_CYCLES",
  CAMPAIGN_NO_OF_DELIVERY: "CAMPAIGN_NO_OF_DELIVERY",
  CAMPAIGN_NO_OF_DELIVERIES: "CAMPAIGN_NO_OF_DELIVERIES",
  CAMPAIGN_ADD_START_END_DATE_TEXT: "CAMPAIGN_ADD_START_END_DATE_TEXT",
  CAMPAIGN_CYCLE: "CAMPAIGN_CYCLE",
  CYCLE: "CYCLE",
  CYCLE_NUMBER: "CYCLE_NUMBER",
  NO_OF_CYCLES: "NO_OF_CYCLES",
  HCM_SINGLE_ROUND: "HCM_SINGLE_ROUND",
  HCM_MULTI_ROUND: "HCM_MULTI_ROUND",
  HCM_MULTIROUND: "HCM_MULTIROUND",
  SINGLEROUND_CAMPAIGN: "SINGLEROUND_CAMPAIGN",
  MULTIROUND_CAMPAIGN: "MULTIROUND_CAMPAIGN",

  // Campaign Summary
  HCM_SUMMARY: "HCM_SUMMARY",
  HCM_CAMPAIGN_SETUP_DETAILS: "HCM_CAMPAIGN_SETUP_DETAILS",
  ES_TQM_SUMMARY_HEADING: "ES_TQM_SUMMARY_HEADING",
  CAMPAIGN_SUMMARY_NA: "CAMPAIGN_SUMMARY_NA",

  // Campaign Status
  STATUS: "STATUS",
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_CREATION_INPROGRESS: "CAMPAIGN_CREATION_INPROGRESS",
  CAMPAIGN_STATUS_CREATING_MESSAGE: "CAMPAIGN_STATUS_CREATING_MESSAGE",
  ACTIVE_STATUS: "ACTIVE_STATUS",
  USER_CREDS_GENERATED: "USER_CREDS_GENERATED",
  GENERATING_USER_CRED: "GENERATING_USER_CRED",
  GENERATING_APK: "GENERATING_APK",

  // Campaign Actions
  CANCEL_CAMPAIGN: "CANCEL_CAMPAIGN",
  DUPLICATE_CAMPAIGN: "DUPLICATE_CAMPAIGN",
  DOWNLOAD_APP: "DOWNLOAD_APP",
  DOWNLOAD_USER_CREDENTIALS: "DOWNLOAD_USER_CREDENTIALS",
  EDIT_CREATING_CAMPAIGN: "EDIT_CREATING_CAMPAIGN",
  EDIT_CAMPAIGN: "EDIT_CAMPAIGN",
  CAMPAIGN_EDIT: "CAMPAIGN_EDIT",
  UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
  HCM_UPDATE_DATE: "HCM_UPDATE_DATE",
  ES_CAMPAIGN_RESPONSE_ACTION: "ES_CAMPAIGN_RESPONSE_ACTION",
  ES_COMMON_TAKE_ACTION: "ES_COMMON_TAKE_ACTION",
  ES_PRODUCT_RESPONSE_ACTION: "ES_PRODUCT_RESPONSE_ACTION",

  // QR Code Popup
  ES_APP_QR: "ES_APP_QR",
  ES_APP_QR_DESC: "ES_APP_QR_DESC",
  ES_CAMPAIGN_CLOSE: "ES_CAMPAIGN_CLOSE",

  // Tutorials
  EXPLORE_TUTORIALS: "EXPLORE_TUTORIALS",

  // ==========================================================================
  // 4. BOUNDARY SELECTION FLOW
  // ==========================================================================
  // Boundary Selection
  CHOOSE_BOUNDARY_LEVEL: "CHOOSE_BOUNDARY_LEVEL",
  CHOOSE_BOUNDARY: "CHOOSE_BOUNDARY",
  CAMPAIGN_SELECT_BOUNDARY: "CAMPAIGN_SELECT_BOUNDARY",
  CAMPAIGN_SELECT_BOUNDARIES_DESCRIPTION: "CAMPAIGN_SELECT_BOUNDARIES_DESCRIPTION",
  HCM_SELECT_BOUNDARY: "HCM_SELECT_BOUNDARY",
  HCM_BOUNDARY_SELECT_HEADING: "HCM_BOUNDARY_SELECT_HEADING",
  HCM_SELECT_BOUNDARY_DESC: "HCM_SELECT_BOUNDARY_DESC",
  HCM_SELECT_BOUNDARY_BUTTON: "HCM_SELECT_BOUNDARY_BUTTON",
  CAMPAIGN_SELECT_BOUNDARY_BUTTON: "CAMPAIGN_SELECT_BOUNDARY_BUTTON",
  HCM_BOUNDARY_INFO: "HCM_BOUNDARY_INFO",
  HCM_CAMPAIGN_ALL_THE_LEVELS_ARE_MANDATORY: "HCM_CAMPAIGN_ALL_THE_LEVELS_ARE_MANDATORY",
  HCM_CAMPAIGN_SELECT_BOUNDARY_DATA_LABEL: "HCM_CAMPAIGN_SELECT_BOUNDARY_DATA_LABEL",
  HCM_CAMPAIGN_SELECT_BOUNDARY_HIERARCHY_LEVEL: "HCM_CAMPAIGN_SELECT_BOUNDARY_HIERARCHY_LEVEL",
  CHANGE_BOUNDARY: "CHANGE_BOUNDARY",
  CAMPAIGN_CANNOT_REMOVE_PREVIOUS_BOUNDARIES: "CAMPAIGN_CANNOT_REMOVE_PREVIOUS_BOUNDARIES",

  // Boundary Update
  ES_CAMPAIGN_UPDATE_BOUNDARY_MODAL_HEADER: "ES_CAMPAIGN_UPDATE_BOUNDARY_MODAL_HEADER",
  ES_CAMPAIGN_UPDATE_BOUNDARY_MODAL_TEXT: "ES_CAMPAIGN_UPDATE_BOUNDARY_MODAL_TEXT",
  HCM_UPDATE_BOUNDARIES: "HCM_UPDATE_BOUNDARIES",
  HCM_EDIT_BOUNDARY_BUTTON: "HCM_EDIT_BOUNDARY_BUTTON",
  ACTION_LABEL_UPDATE_BOUNDARY_DETAILS: "ACTION_LABEL_UPDATE_BOUNDARY_DETAILS",

  // Boundary Details
  HCM_BOUNDARY_DETAILS: "HCM_BOUNDARY_DETAILS",
  HCM_SHOW_LESS_SELECTED: "HCM_SHOW_LESS_SELECTED",
  HCM_SELECTED: "HCM_SELECTED",
  HCM_SHOW_MORE_ALL: "HCM_SHOW_MORE_ALL",
  HCM_BOUNDARY_CLOSE: "HCM_BOUNDARY_CLOSE",
  BOUNDARY: "BOUNDARY",
  ADD_BOUNDARY: "ADD _BOUNDARY",

  // Boundary Filter
  BUTTON_FILTER_BY_BOUNDARY: "BUTTON_FILTER_BY_BOUNDARY",

  // ==========================================================================
  // 5. BOUNDARY DATA MANAGEMENT FLOW
  // ==========================================================================
  // Boundary Management Home
  BOUNDARY_MANAGEMENT: "BOUNDARY_MANAGEMENT",
  BOUNDARY_DATA_MANAGEMENT: "BOUNDARY_DATA_MANAGEMENT",
  CURRENT_HIERARCHIES: "CURRENT_HIERARCHIES",
  DATA_SYNC_WITH_SERVER: "DATA_SYNC_WITH_SERVER",
  ES_BOUNDARY_SUMMARY_HEADING: "ES_BOUNDARY_SUMMARY_HEADING",
  CURRENT_HIERARCHY_TYPE_IS: "CURRENT_HIERARCHY_TYPE_IS",

  // Hierarchy Management
  HIERARCHY: "HIERARCHY",
  HIERARCHY_CREATED_ON: "HIERARCHY_CREATED_ON",
  HIERARCHY_LAST_MODIFIED_ON: "HIERARCHY_LAST_MODIFIED_ON",
  CREATE_BOUNDARY_HIERARCHY: "CREATE_BOUNDARY_HIERARCHY",
  BOUNDARY_HIERARCHY_INFO_MSG: "BOUNDARY_HIERARCHY_INFO_MSG",
  ADD_HIERARCHY_LEVEL: "ADD_HIERARCHY_LEVEL",
  CMN_ATLEAST_ONE_HIERARCHY: "CMN_ATLEAST_ONE_HIERARCHY",
  CMN_FILLORDELETE_CREATED_HIERARCHY: "CMN_FILLORDELETE_CREATED_HIERARCHY",
  LEVEL: "LEVEL",
  LEVELS_CANNOT_BE_EMPTY: "LEVELS_CANNOT_BE_EMPTY",
  YOU_WONT_BE_ABLE_TO_UNDO_THIS_STEP: "YOU_WON'T_BE_ABLE_TO_UNDO_THIS_STEP_OF_CREATING_HIERARCHY",

  // Boundary Creation
  CREATE_NEW_BOUNDARY_DATA: "CREATE_NEW_BOUNDARY_DATA",
  EDIT_BOUNDARY_DATA: "EDIT_BOUNDARY_DATA",
  VIEW_EXISTING_BOUNDARY_DATA: "VIEW_EXISTING_BOUNDARY_DATA",
  CHOOSE_MEANS_TO_CREATE_BOUNDARY: "CHOOSE_MEANS_TO_CREATE_BOUNDARY",
  GET_BOUNDARY_DATA_FROM_GEOPODE: "GET_BOUNDARY_DATA_FROM_GEOPODE",
  CREATE_MY_OWN_BOUNDARY_DATA: "CREATE_MY_OWN_BOUNDARY_DATA",
  BOUNDARY_DATA_FROM_GEOPODE: "BOUNDARY_DATA_FROM_GEOPODE",
  NEWLY_ADDED_BOUNDARY_DATA: "NEWLY_ADDED_BOUNDARY_DATA",

  // Boundary Upload & Templates
  UPLOAD_EXCEL: "UPLOAD_EXCEL",
  UPLOAD_EXCEL_FOR_ALL_BOUNDARIES: "UPLOAD_EXCEL_FOR_ALL_BOUNDARIES",
  DOWNLOAD_EXCEL_TEMPLATE: "DOWNLOAD_EXCEL_TEMPLATE",
  DOWNLOAD_TEMPLATE_BOUNDARY: "DOWNLOAD_TEMPLATE_BOUNDARY",
  BOUNDARY_DOWNLOAD_MESSAGE: "BOUNDARY_DOWNLOAD_MESSAGE",
  DOWNLOAD_EXCEL_TEMPLATE_FOR_BOUNDARY: "DOWNLOAD_EXCEL_TEMPLATE_FOR_BOUNDARY",

  // Boundary Confirmation
  CONFIRM_BOUNDARY_DATA: "CONFIRM_BOUNDARY_DATA",
  CMN_BOUNDARY_REL_DATA_CREATE_PREVIEW: "CMN_BOUNDARY_REL_DATA_CREATE_PREVIEW",
  CMN_BOUNDARY_REL_DATA_CREATE: "CMN_BOUNDARY_REL_DATA_CREATE",
  CMN_BOUNDARY_REL_CREATE: "CMN_BOUNDARY_REL_CREATE",

  // Boundary Map Preview
  PREVIEW_ON_MAP: "PREVIEW_ON_MAP",
  LAYERS: "LAYERS",

  // Boundary Validation Errors
  BOUNDARY_COLUMN: "BOUNDARY_COLUMN",
  BOUNDARY_EMPTY: "BOUNDARY_EMPTY",
  BOUNDARY_EMPTY_SHEET: "BOUNDARY_EMPTY_SHEET",
  BOUNDARY_FILLED: "BOUNDARY_FILLED",
  BOUNDARY_NO_VALID_ROWS: "BOUNDARY_NO_VALID_ROWS",
  BOUNDARY_ROW: "BOUNDARY_ROW",
  HCM_BOUNDARY_INVALID_SHEET: "HCM_BOUNDARY_INVALID_SHEET",
  HCM_INVALID_BOUNDARY_SHEET: "HCM_INVALID_BOUNDARY_SHEET",
  HCM_BOUNDARY_MESSAGE: "HCM_BOUNDARY_MESSAGE",
  MULTIPLE_COUNTRIES_CANNOT_EXIST: "MULTIPLE_COUNTRIES_CANNOT_EXIST",

  // ==========================================================================
  // 6. UPLOAD DATA FLOW
  // ==========================================================================
  // Upload Data Main
  HCM_UPLOAD_DATA: "HCM_UPLOAD_DATA",
  HCM_ADMIN_CONSOLE_UPLOAD_DATA: "HCM_ADMIN_CONSOLE_UPLOAD_DATA",
  HCM_DATA_UPLOAD: "HCM_DATA_UPLOAD",
  HCM_DATA_UPLOAD_SUMMARY: "HCM_DATA_UPLOAD_SUMMARY",
  HCM_UPLOAD_DATA_BUTTON: "HCM_UPLOAD_DATA_BUTTON",
  HCM_EDIT_UPLOAD_DATA_BUTTON: "HCM_EDIT_UPLOAD_DATA_BUTTON",
  ACTION_UPLOAD_SCREEN: "ACTION_UPLOAD_SCREEN",

  // Upload Types
  HCM_UPLOAD_FACILITY: "HCM_UPLOAD_FACILITY",
  HCM_UPLOAD_FACILITY_MAPPING: "HCM_UPLOAD_FACILITY_MAPPING",
  HCM_UPLOAD_USER: "HCM_UPLOAD_USER",
  HCM_UPLOAD_USER_MAPPING: "HCM_UPLOAD_USER_MAPPING",
  HCM_UPLOAD_TARGET: "HCM_UPLOAD_TARGET",
  WBH_UPLOAD_FACILITY: "WBH_UPLOAD_FACILITY",
  WBH_UPLOAD_TARGET: "WBH_UPLOAD_TARGET",
  WBH_UPLOAD_USER: "WBH_UPLOAD_USER",

  // Download Current Data
  WBH_DOWNLOAD_CURRENT_FACILITY: "WBH_DOWNLOAD_CURRENT_FACILITY",
  WBH_DOWNLOAD_CURRENT_TARGET: "WBH_DOWNLOAD_CURRENT_TARGET",
  WBH_DOWNLOAD_CURRENT_USER: "WBH_DOWNLOAD_CURRENT_USER",
  HCM_CAMPAIGN_DOWNLOAD_TEMPLATE: "HCM_CAMPAIGN_DOWNLOAD_TEMPLATE",

  // Upload Modal Headers
  ES_CAMPAIGN_UPLOAD_BOUNDARY_DATA_MODAL_HEADER: "ES_CAMPAIGN_UPLOAD_BOUNDARY_DATA_MODAL_HEADER",
  ES_CAMPAIGN_UPLOAD_BOUNDARY_DATA_MODAL_TEXT: "ES_CAMPAIGN_UPLOAD_BOUNDARY_DATA_MODAL_TEXT",
  ES_CAMPAIGN_UPLOAD_FACILITY_DATA_MODAL_HEADER: "ES_CAMPAIGN_UPLOAD_FACILITY_DATA_MODAL_HEADER",
  ES_CAMPAIGN_UPLOAD_FACILITY_DATA_MODAL_TEXT: "ES_CAMPAIGN_UPLOAD_FACILITY_DATA_MODAL_TEXT",
  ES_CAMPAIGN_UPLOAD_USER_DATA_MODAL_HEADER: "ES_CAMPAIGN_UPLOAD_USER_DATA_MODAL_HEADER",
  ES_CAMPAIGN_UPLOAD_USER_DATA_MODAL_TEXT: "ES_CAMPAIGN_UPLOAD_USER_DATA_MODAL_TEXT",

  // Facility Details
  HCM_ADMIN_CONSOLE_AVAILABLE_FACILITIES: "HCM_ADMIN_CONSOLE_AVAILABLE_FACILITIES",
  HCM_ADMIN_CONSOLE_FACILITIES: "HCM_ADMIN_CONSOLE_FACILITIES",
  HCM_ADMIN_CONSOLE_FACILITY_CODE: "HCM_ADMIN_CONSOLE_FACILITY_CODE",
  HCM_ADMIN_CONSOLE_FACILITY_USAGE: "HCM_ADMIN_CONSOLE_FACILITY_USAGE",
  FACILITY_DETAILS: "FACILITY_DETAILS",
  FACILITY_NAME: "FACILITY_NAME",
  FACILITY_STATUS: "FACILITY_STATUS",
  FACILITY_TYPE: "FACILITY_TYPE",
  FACILITY_USAGE: "FACILITY_USAGE",
  FACILITY_DETAILS_ERROR: "FACILITY_DETAILS_ERROR",
  FACILITY_FILE_MISSING: "FACILITY_FILE_MISSING",
  FACILITY_MAPPING_POP_HEADER: "FACILITY_MAPPING_POP_HEADER",
  HCM_FACILITY_MESSAGE: "HCM_FACILITY_MESSAGE",
  HCM_FACILITY_USAGE_VALIDATION: "HCM_FACILITY_USAGE_VALIDATION",
  HCM_INVALID_FACILITY_SHEET: "HCM_INVALID_FACILITY_SHEET",
  HCM_CAMPAIGN_CONSOLE_FACILITY_NAME_TYPE_ERROR: "HCM_CAMPAIGN_CONSOLE_FACILITY_NAME_TYPE_ERROR",
  ONE_FACILITY_ATLEAST_SHOULD_BE_ACTIVE: "ONE_FACILITY_ATLEAST_SHOULD_BE_ACTIVE",
  NO_BOUNDARY_SELECTED_FOR_ACTIVE_FACILITY: "NO_BOUNDARY_SELECTED_FOR_ACTIVE_FACILITY",

  // User Details
  HCM_ADMIN_CONSOLE_USER_LIST: "HCM_ADMIN_CONSOLE_USER_LIST",
  USER_DETAILS: "USER_DETAILS",
  USER_GENERATE_DETAILS: "USER_GENERATE_DETAILS",
  USER_DETAILS_ERROR: "USER_DETAILS_ERROR",
  USER_FILE_MISSING: "USER_FILE_MISSING",
  USER_MAPPING_POP_HEADER: "USER_MAPPING_POP_HEADER",
  HCM_USER_MESSAGE: "HCM_USER_MESSAGE",
  HCM_INVALID_USER_SHEET: "HCM_INVALID_USER_SHEET",
  HCM_CAMPAIGN_CONSOLE_USER_NAME_TYPE_ERROR: "HCM_CAMPAIGN_CONSOLE_USER_NAME_TYPE_ERROR",
  HCM_MORE_USER: "HCM_MORE_USER",
  NAME_OF_PERSON: "NAME_OF_PERSON",
  PHONE_NUMBER: "PHONE_NUMBER",
  ROLE: "ROLE",
  EMPLOYEMENT_TYPE: "EMPLOYEMENT_TYPE",
  ONE_USER_ATLEAST_SHOULD_BE_ACTIVE: "ONE_USER_ATLEAST_SHOULD_BE_ACTIVE",
  NO_BOUNDARY_SELECTED_FOR_ACTIVE_USER: "NO_BOUNDARY_SELECTED_FOR_ACTIVE_USER",

  // Target Details
  HCM_ADMIN_CONSOLE_TARGET_AT_THE_SELECTED_BOUNDARY_LEVEL: "HCM_ADMIN_CONSOLE_TARGET_AT_THE_SELECTED_BOUNDARY_LEVEL",
  TARGET_DETAILS: "TARGET_DETAILS",
  TARGET_DETAILS_ERROR: "TARGET_DETAILS_ERROR",
  TARGET_FILE_MISSING: "TARGET_FILE_MISSING",
  HCM_MISSING_TARGET: "HCM_MISSING_TARGET",
  HCM_TARGET_VALIDATION_ERROR: "HCM_TARGET_VALIDATION_ERROR",

  // Boundary Data Upload
  HCM_ADMIN_CONSOLE_BOUNDARY_DATA: "HCM_ADMIN_CONSOLE_BOUNDARY_DATA",
  HCM_ADMIN_CONSOLE_BOUNDARY_CODE: "HCM_ADMIN_CONSOLE_BOUNDARY_CODE",
  HCM_ADMIN_CONSOLE_DATA: "HCM_ADMIN_CONSOLE_DATA",

  // Mapping
  UPLOAD_DATA_MAPPING: "UPLOAD_DATA_MAPPING",
  ADD_DATA_MAPPING: "ADD_DATA_MAPPING",
  EDIT_DATA_MAPPING: "EDIT_DATA_MAPPING",
  MAPPING_ADD_DATA: "MAPPING_ADD_DATA",
  MAPPING_DELETE: "MAPPING_DELETE",
  MAPPING_EDIT: "MAPPING_EDIT",
  MAPPING_EDIT_DATA: "MAPPING_EDIT_DATA",
  UPLOAD_MAPPING_ERROR: "UPLOAD_MAPPING_ERROR",
  HCM_MAPPING_NO_BOUNDARY_ERROR: "HCM_MAPPING_NO_BOUNDARY_ERROR",

  // Upload Validation
  HCM_CHECK_FILE_AGAIN: "HCM_CHECK_FILE_AGAIN",
  HCM_CAMPAIGN_UPLOAD_CANCEL: "HCM_CAMPAIGN_UPLOAD_CANCEL",
  HCM_FILE_UNAVAILABLE: "HCM_FILE_UNAVAILABLE",
  HCM_EMPTY_SHEET: "HCM_EMPTY_SHEET",
  HCM_FILLED: "HCM_FILLED",
  HCM_MISSING_HEADERS: "HCM_MISSING_HEADERS",
  HCM_README_SHEETNAME: "HCM_README_SHEETNAME",

  // Upload Error Messages
  HCM_DATA_ALLOWED_VALUES_ARE: "HCM_DATA_ALLOWED_VALUES_ARE",
  HCM_DATA_AT_ROW: "HCM_DATA_AT_ROW",
  HCM_DATA_SHOULD_BE_10_DIGIT: "HCM_DATA_SHOULD_BE_10_DIGIT",
  HCM_DATA_SHOULD_NOT_BE_EMPTY: "HCM_DATA_SHOULD_NOT_BE_EMPTY",
  HCM_IN_COLUMN: "HCM_IN_COLUMN",
  HCM_IS_INVALID: "HCM_IS_INVALID",
  COLUMN: "COLUMN",
  ROW: "Row",

  // ==========================================================================
  // 7. UPLOAD LOCALIZATION FLOW
  // ==========================================================================
  HCM_UPLOAD_LOCALIZATION_DATA_HEADING: "HCM_UPLOAD_LOCALIZATION_DATA_HEADING",
  HCM_UPLOAD_LOCALIZATION_DATA_DESC: "HCM_UPLOAD_LOCALIZATION_DATA_DESC",
  ADD_TRANSLATIONS: "ADD_TRANSLATIONS",
  ADD_LOCALIZATION: "ADD_LOCALIZATION",
  ADD_HEADER_LOCALIZATION: "ADD_HEADER_LOCALIZATION",
  SAVE_TRANSLATIONS: "SAVE_TRANSLATIONS",
  ENTER_TRANSLATION: "ENTER_TRANSLATION",
  ADD_LOCALISATION_BREADCRUMB : "ADD_LOCALISATION_BREADCRUMB",

  // Localization Module Selection
  HCM_CHOOSE_MODULE: "HCM_CHOOSE_MODULE",
  DIGIT_LOC_SELECT_MODULE_LABEL: "DIGIT_LOC_SELECT_MODULE_LABEL",
  DIGIT_LOC_SELECT_MODULE_PLACEHOLDER: "DIGIT_LOC_SELECT_MODULE_PLACEHOLDER",

  // Localization Bulk Upload
  DIGIT_LOC_BULK_UPLOAD_BUTTON: "DIGIT_LOC_BULK_UPLOAD_BUTTON",
  DIGIT_LOC_BULK_UPLOAD_HEADER: "DIGIT_LOC_BULK_UPLOAD_HEADER",
  DIGIT_LOC_BULK_UPLOAD_XLS: "DIGIT_LOC_BULK_UPLOAD_XLS",
  DIGIT_LOC_DOWNLOAD_TEMPLATE: "DIGIT_LOC_DOWNLOAD_TEMPLATE",
  DIGIT_LOC_MODAL_CANCEL: "DIGIT_LOC_MODAL_CANCEL",
  DIGIT_LOC_MODAL_SUBMIT: "DIGIT_LOC_MODAL_SUBMIT",

  // ==========================================================================
  // 8. DELIVERY RULES CONFIGURATION FLOW
  // ==========================================================================
  // Delivery Main
  HCM_DELIVERY_HEADING: "HCM_DELIVERY_HEADING",
  HCM_DELIVERY_DESC: "HCM_DELIVERY_DESC",
  HCM_DELIVERY_BUTTON: "HCM_DELIVERY_BUTTON",
  HCM_EDIT_DELIVERY_BUTTON: "HCM_EDIT_DELIVERY_BUTTON",
  HCM_EDIT_DELIVERY_DATES: "HCM_EDIT_DELIVERY_DATES",
  HCM_DELIVERY_TYPE: "HCM_DELIVERY_TYPE",
  HCM_DELIVERY_DETAILS: "HCM_DELIVERY_DETAILS",
  HCM_DELIVERY_DETAILS_SUMMARY: "HCM_DELIVERY_DETAILS_SUMMARY",
  CAMPAIGN_DELIVERY_DETAILS: "CAMPAIGN_DELIVERY_DETAILS",
  ES_CAMPAIGN_UPDATE_DELIVERY_DETAILS: "ES_CAMPAIGN_UPDATE_DELIVERY_DETAILS",
  ES_CAMPAIGN_DELIVERY_BACK: "ES_CAMPAIGN_DELIVERY_BACK",
  ES_CAMPAIGN_DELIVERY_SUBMIT: "ES_CAMPAIGN_DELIVERY_SUBMIT",

  // Delivery Tabs
  CAMPAIGN_DELIVERY: "CAMPAIGN_DELIVERY",
  CAMPAIGN_DELIVERY_TAB_SUB_TEXT: "CAMPAIGN_DELIVERY_TAB_SUB_TEXT",
  DELIVERY_NUMBER: "DELIVERY_NUMBER",

  // Delivery Rules
  CAMPAIGN_DELIVERY_RULE_LABEL: "CAMPAIGN_DELIVERY_RULE_LABEL",
  CAMPAIGN_ATTRIBUTE_LABEL: "CAMPAIGN_ATTRIBUTE_LABEL",
  CAMPAIGN_OPERATOR_LABEL: "CAMPAIGN_OPERATOR_LABEL",
  CAMPAIGN_VALUE_LABEL: "CAMPAIGN_VALUE_LABEL",
  CAMPAIGN_FROM_LABEL: "CAMPAIGN_FROM_LABEL",
  CAMPAIGN_TO_LABEL: "CAMPAIGN_TO_LABEL",
  CAMPAIGN_DELETE_ROW_TEXT: "CAMPAIGN_DELETE_ROW_TEXT",
  CAMPAIGN_ADD_MORE_ATTRIBUTE_TEXT: "CAMPAIGN_ADD_MORE_ATTRIBUTE_TEXT",
  CAMPAIGN_DELETE_CONDITION_LABEL: "CAMPAIGN_DELETE_CONDITION_LABEL",
  CAMPAIGN_CONDITION: "CAMPAIGN_CONDITION",
  CAMPAIGN_ADD_MORE_DELIVERY_BUTTON: "CAMPAIGN_ADD_MORE_DELIVERY_BUTTON",
  ATTRIBUTE: "Attribute",
  OPERATOR: "Operator",
  VALUE: "Value",

  // Product Management in Delivery
  CAMPAIGN_ADD_PRODUCTS_BUTTON_TEXT: "CAMPAIGN_ADD_PRODUCTS_BUTTON_TEXT",
  CAMPAIGN_PRODUCTS_MODAL_HEADER_TEXT: "CAMPAIGN_PRODUCTS_MODAL_HEADER_TEXT",
  CAMPAIGN_PRODUCTS_MODAL_SUBMIT_TEXT: "CAMPAIGN_PRODUCTS_MODAL_SUBMIT_TEXT",
  CAMPAIGN_ADD_PRODUCTS_LABEL: "CAMPAIGN_ADD_PRODUCTS_LABEL",
  CAMPAIGN_PRODUCT_LABEL: "CAMPAIGN_PRODUCT_LABEL",
  PRODUCT: "Product",
  COUNT: "Count",

  // ==========================================================================
  // 9. PRODUCT MANAGEMENT FLOW
  // ==========================================================================
  // Product Creation
  HCM_CAMPAIGN_ADD_NEW_PRODUCT_HEADER: "HCM_CAMPAIGN_ADD_NEW_PRODUCT_HEADER",
  HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_PRE_TEXT: "HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_PRE_TEXT",
  HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_BOLD_TEXT: "HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_BOLD_TEXT",
  HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_POST_TEXT: "HCM_CAMPAIGN_ADD_NEW_PRODUCT_DESCRIPTION_POST_TEXT",
  ES_ADD_PRODUCT_TITLE: "ES_ADD_PRODUCT_TITLE",
  ES_CAMPAIGN_ADD_PRODUCT_BUTTON: "ES_CAMPAIGN_ADD_PRODUCT_BUTTON",
  CAMPAIGN_ADD_MORE_PRODUCT_BUTTON: "CAMPAIGN_ADD_MORE_PRODUCT_BUTTON",

  // Product Details
  HCM_PRODUCT_NAME: "HCM_PRODUCT_NAME",
  HCM_PRODUCT_TYPE: "HCM_PRODUCT_TYPE",
  HCM_PRODUCT_VARIANT: "HCM_PRODUCT_VARIANT",

  // Product Validation
  CAMPAIGN_ADD_PRODUCT_MANDATORY_ERROR: "CAMPAIGN_ADD_PRODUCT_MANDATORY_ERROR",
  CAMPAIGN_PRODUCT_NAME_ERROR: "CAMPAIGN_PRODUCT_NAME_ERROR",
  CAMPAIGN_PRODUCT_VARIANT_ERROR: "CAMPAIGN_PRODUCT_VARIANT_ERROR",
  DUPLICATE_PRODUCT_VARIANT_ERROR: "DUPLICATE_PRODUCT_VARIANT_ERROR",

  // Product Resources
  CAMPAIGN_RESOURCE: "CAMPAIGN_RESOURCE",
  CAMPAIGN_COUNT_LABEL: "CAMPAIGN_COUNT_LABEL",
  CAMPAIGN_NEW_PRODUCT_TEXT: "CAMPAIGN_NEW_PRODUCT_TEXT",
  ES_CAMPAIGN_ADD_PRODUCT_LINK: "ES_CAMPAIGN_ADD_PRODUCT_LINK",
  RESOURCES: "RESOURCES",

  // ==========================================================================
  // 10. APP CONFIGURATION FLOW
  // ==========================================================================
  // App Configuration Main
  APP_CONFIGURATION: "APP_CONFIGURATION",
  APP_CONFIGURATION_REDESIGN: "APP_CONFIGURATION_REDESIGN",
  ACTION_LABEL_CONFIGURE_APP: "ACTION_LABEL_CONFIGURE_APP",
  "ACTION_TEST_APP_CONFIGURATION_3.0": "ACTION_TEST_APP_CONFIGURATION_3.0",

  // Mobile App
  HCM_MOBILE_APP_HEADING: "HCM_MOBILE_APP_HEADING",
  HCM_MOBILE_APP_DESC: "HCM_MOBILE_APP_DESC",
  HCM_MOBILE_APP_BUTTON_EDIT: "HCM_MOBILE_APP_BUTTON_EDIT",
  HCM_MOBILE_APP_BUTTON: "HCM_MOBILE_APP_BUTTON",
  HCM_DOWNLOAD_CREDENTIALS: "HCM_DOWNLOAD_CREDENTIALS",
  HCM_DOWNLOAD_APP: "HCM_DOWNLOAD_APP",
  CAMPAIGN_DOWNLOAD_USER_CRED: "CAMPAIGN_DOWNLOAD_USER_CRED",
  ES_CAMPAIGN_DOWNLOAD_USER_DETAILS: "ES_CAMPAIGN_DOWNLOAD_USER_DETAILS",

  // App Modules
  APP_FEATURES: "APP_FEATURES",
  DIGIT_HCM_COMPLAINTS_MODULE: "DIGIT_HCM_COMPLAINTS_MODULE",
  DIGIT_HCM_DELIVERY_MODULE: "DIGIT_HCM_DELIVERY_MODULE",
  DIGIT_HCM_HFREFERRAL_MODULE: "DIGIT_HCM_HFREFERRAL_MODULE",
  DIGIT_HCM_INVENTORY_MODULE: "DIGIT_HCM_INVENTORY_MODULE",
  DIGIT_HCM_REGISTRATION_MODULE: "DIGIT_HCM_REGISTRATION_MODULE",

  // App Config Fields
  APPCONFIG_HEAD_FIELDS: "APPCONFIG_HEAD_FIELDS",
  APPCONFIG_SUBHEAD_FIELDS: "APPCONFIG_SUBHEAD_FIELDS",
  APPCONFIG_SUBHEAD_BUTTONS: "APPCONFIG_SUBHEAD_BUTTONS",
  APPCONFIG_PROPERTIES: "APPCONFIG_PROPERTIES",
  TIP_APPCONFIG_HEAD_FIELDS: "TIP_APPCONFIG_HEAD_FIELDS",
  TIP_APPCONFIG_SUBHEAD_FIELDS: "TIP_APPCONFIG_SUBHEAD_FIELDS",
  TIP_APPCONFIG_SUBHEAD_BUTTONS: "TIP_APPCONFIG_SUBHEAD_BUTTONS",
  TIP_APPCONFIG_PROPERTIES: "TIP_APPCONFIG_PROPERTIES",

  // Field Configuration
  FIELD_CONFIGURATION: "FIELD_CONFIGURATION",
  FIELD_LABEL: "FIELD_LABEL",
  FIELD_TYPE: "FIELD_TYPE",
  SELECT_FIELD_TYPE: "SELECT_FIELD_TYPE",
  ENTER_FIELD_LABEL: "ENTER_FIELD_LABEL",
  ADD_FIELD: "ADD_FIELD",
  ADD_SECTION: "ADD_SECTION",
  DEPENDENT_FIELD_TAG: "DEPENDENT_FIELD_TAG",
  CMP_DRAWER_FIELD_DISABLED_SINCE_HIDDEN: "CMP_DRAWER_FIELD_DISABLED_SINCE_HIDDEN",
  MANDATORY_FIELD_PROPERTIES_DISABLE_HOVER_TEXT: "MANDATORY_FIELD_PROPERTIES_DISABLE_HOVER_TEXT",

  // Navigation & Flows
  NAVIGATION_LOGIC: "NAVIGATION_LOGIC",
  TIP_NAVIGATION_LOGIC: "TIP_NAVIGATION_LOGIC",
  APP_CONFIG_FLOWS: "APP_CONFIG_FLOWS",
  APP_CONFIG_NO_FLOW_CONFIG_FOUND: "APP_CONFIG_NO_FLOW_CONFIG_FOUND",
  APP_CONFIG_NO_PAGE_CONFIG_FOUND: "APP_CONFIG_NO_PAGE_CONFIG_FOUND",

  // App Config Errors & Status
  APP_CONFIG_NO_CONFIGURATION_DATA_AVAILABLE: "APP_CONFIG_NO_CONFIGURATION_DATA_AVAILABLE",
  APP_CONFIG_NO_FIELD_SELECTED: "APP_CONFIG_NO_FIELD_SELECTED",
  APP_CONFIG_NO_ROLES_ASSIGNED: "APP_CONFIG_NO_ROLES_ASSIGNED",
  APP_CONFIG_ROLES: "APP_CONFIG_ROLES",
  APP_CONFIG_ACTION_BUTTON_LABEL: "APP_CONFIG_ACTION_BUTTON_LABEL",

  // ==========================================================================
  // 11. CHECKLIST FLOW
  // ==========================================================================
  // Checklist Main
  CREATE_CHECKLIST: "CREATE_CHECKLIST",
  SEARCH_CHECKLIST: "SEARCH_CHECKLIST",
  CREATE_NEW_CHECKLIST: "CREATE_NEW_CHECKLIST",
  CONFIGURE_CHECKLIST: "CONFIGURE_CHECKLIST",
  VIEW_CHECKLIST: "VIEW_CHECKLIST",
  UPDATE_CHECKLIST: "UPDATE_CHECKLIST",
  PREVIEW_CHECKLIST: "PREVIEW_CHECKLIST",
  CHECKLIST_PREVIEW: "CHECKLIST_PREVIEW",
  ACTION_CREATE_CHECKLIST: "ACTION_CREATE_CHECKLIST",
  ACTION_VIEW_CHECKLIST: "ACTION_VIEW_CHECKLIST",
  ACTION_UPDATE_CHECKLIST: "ACTION_UPDATE_CHECKLIST",

  // Checklist Heading & Buttons
  HCM_CHECKLIST_HEADING: "HCM_CHECKLIST_HEADING",
  HCM_CHECKLIST_DESC: "HCM_CHECKLIST_DESC",
  HCM_CHECKLIST_BUTTON: "HCM_CHECKLIST_BUTTON",
  HCM_CHECKLIST_CREATE: "HCM_CHECKLIST_CREATE",
  HCM_CHECKLIST_VIEW: "HCM_CHECKLIST_VIEW",
  CHECKLIST_TOBE_CONFIGURED: "CHECKLIST_TOBE_CONFIGURED",

  // Checklist Configuration
  NAME_OF_CHECKLIST: "NAME_OF_CHECKLIST",
  CHECKLIST_HELP_TEXT: "CHECKLIST_HELP_TEXT",
  CHECKLIST_HELP_TEXT_PALCEHOLDER: "CHECKLIST_HELP_TEXT_PALCEHOLDER",
  HCM_CHECKLIST_CLEAR: "HCM_CHECKLIST_CLEAR",
  HCM_CHECKLIST_OPTION: "HCM_CHECKLIST_OPTION",
  HCM_CHECKLIST_QUESTION: "HCM_CHECKLIST_QUESTION",
  ADD_QUESTION: "ADD_QUESTION",
  CREATE_QUESTION: "CREATE_QUESTION",
  CAMPAIGN_DELETE_QUESTION: "CAMPAIGN_DELETE_QUESTION",
  QUESTION: "QUESTION",
  TYPE_YOUR_QUESTION_HERE: "TYPE_YOUR_QUESTION_HERE",
  ADD_OPTIONS: "ADD_OPTIONS",
  OPTION_PLACEHOLDER: "OPTION_PLACEHOLDER",

  // Checklist Error
  CAMPAIGN_CANNOT_CLICK: "CAMPAIGN_CANNOT_CLICK",

  // ==========================================================================
  // 12. MY CAMPAIGNS FLOW
  // ==========================================================================
  MY_CAMPAIGNS: "MY_CAMPAIGNS",
  MY_CAMPAIGN: "MY_CAMPAIGN",
  ACTION_TEST_MY_CAMPAIGN_NEW: "ACTION_TEST_MY_CAMPAIGN_NEW",
  CAMPAIGN_SEARCH_TITLE: "CAMPAIGN_SEARCH_TITLE",

  // Campaign List
  COMMON_NO_RESULTS_FOUND: "COMMON_NO_RESULTS_FOUND",
  NO_RESULTS_FOUND: "NO_RESULTS_FOUND",
  FILTER_BY_ACTIVE_STATUS: "FILTER_BY_ACTIVE_STATUS",
  NO_TABLE_COLUMNS_FOUND: "NO_TABLE_COLUMNS_FOUND",

  // Clone Campaign
  HCM_CREATE_COPY_OF_CAMPAIGN: "HCM_CREATE_COPY_OF_CAMPAIGN",
  CREATE_COPY: "CREATE_COPY",

  // ==========================================================================
  // 13. DATE AND CYCLE UPDATE FLOW
  // ==========================================================================
  UPDATE_DATE_AND_CYCLE_HEADER: "UPDATE_DATE_AND_CYCLE_HEADER",
  HCM_CAMPAIGN_DATES_CHANGE_BOUNDARY_HEADER: "HCM_CAMPAIGN_DATES_CHANGE_BOUNDARY_HEADER",
  HCM_CAMPAIGN_DATES_CHANGE_BOUNDARY_SUB_TEXT: "HCM_CAMPAIGN_DATES_CHANGE_BOUNDARY_SUB_TEXT",
  ACTION_LABEL_UPDATE_DATES: "ACTION_LABEL_UPDATE_DATES",
  UPDATE_DATE_CHANGE: "UPDATE_DATE_CHANGE",
  CAMPAIGN_UPDATE_DATE_SUBMIT: "CAMPAIGN_UPDATE_DATE_SUBMIT",
  ES_CAMPAIGN_CHANGE_DATE_CONFIRM: "ES_CAMPAIGN_CHANGE_DATE_CONFIRM",

  // Date Update Errors
  SELECT_BOUNDARY_LEVEL_ERROR: "SELECT_BOUNDARY_LEVEL_ERROR",
  SELECT_DATE_CHANGE_MANDATORY_ERROR: "SELECT_DATE_CHANGE_MANDATORY_ERROR",
  UPDATE_DATE_MANDATORY_FIELDS_MISSING: "UPDATE_DATE_MANDATORY_FIELDS_MISSING",

  // Date Update Success
  HCM_DATE_CHANGE_VIEW_SUCCESS_RESPONSE_ACTION: "HCM_DATE_CHANGE_VIEW_SUCCESS_RESPONSE_ACTION",
  HCM_DATE_CHANGE_SUCCESS_RESPONSE_ACTION: "HCM_DATE_CHANGE_SUCCESS_RESPONSE_ACTION",

  // ==========================================================================
  // 14. MICROPLAN INTEGRATION FLOW
  // ==========================================================================
  MY_MICROPLANS_HEADING: "MY_MICROPLANS_HEADING",
  MY_FETCH_FROM_MICROPLAN_HEADING: "MY_FETCH_FROM_MICROPLAN_HEADING",
  ACTION_TEST_SETUP_CAMPAIGN_FROM_MICROPLAN: "ACTION_TEST_SETUP_CAMPAIGN_FROM_MICROPLAN",
  HCM_FETCH_FROM_PLAN_INFO: "HCM_FETCH_FROM_PLAN_INFO",
  MP_COMPELTED_STEPS: "MP_COMPELTED_STEPS",
  MP_OUT_OFF: "MP_OUT_OFF",

  // ==========================================================================
  // 15. TIMELINE & PROGRESS TRACKING
  // ==========================================================================
  HCM_TIMELINE: "HCM_TIMELINE",
  ES_CAMPAIGN_TIMELINE: "ES_CAMPAIGN_TIMELINE",
  HCM_TIMELINE_POPUP: "HCM_TIMELINE_POPUP",
  ACTION_LABEL_VIEW_TIMELINE: "ACTION_LABEL_VIEW_TIMELINE",

  // ==========================================================================
  // 16. DOCUMENTS & RESOURCES
  // ==========================================================================
  CAMPAIGN_DOCUMENT_TITLE: "CAMPAIGN_DOCUMENT_TITLE",
  ES_CAMPAIGN_NO_DOCUMENTS_AVAILABLE: "ES_CAMPAIGN_NO_DOCUMENTS_AVAILABLE",
  NO_DOCUMENTS_AVAILABLE: "NO_DOCUMENTS_AVAILABLE",

  // ==========================================================================
  // 17. NATIONAL DASHBOARD & DSS
  // ==========================================================================
  NATIONAL_DASHBOARD: "NATIONAL_DASHBOARD",
  ACTION_TEST_NATDASHBOARD: "ACTION_TEST_NATDASHBOARD",
  ES_TITLE_DSS: "ES_TITLE_DSS",
  ACTION_TEST_SURE_DASHBOARD: "ACTION_TEST_SURE_DASHBOARD",
  DSS_CARD_HEADER_DASHBOARD: "DSS_CARD_HEADER_DASHBOARD",
  NDSS_DASHBOARD: "NDSS_DASHBOARD",
  PROVINCIAL_DASHBOARD: "PROVINCIAL_DASHBOARD",
  DISTRICT_DASHBOARD: "DISTRICT_DASHBOARD",
  REFERRAL_DASHBOARD: "REFERRAL_DASHBOARD",

  // ==========================================================================
  // 18. MULTI-TAB & PROJECT CONTEXT
  // ==========================================================================
  CAMPAIGN_PROJECT: "CAMPAIGN_PROJECT",

  // ==========================================================================
  // 19. API & REQUEST HANDLING
  // ==========================================================================
  CM_CREATE_REQUEST: "CM_CREATE_REQUEST",
  CM_UPDATE_REQUEST: "CM_UPDATE_REQUEST",
  HCM_CAMPAIGN_MANAGER_UPLOAD_ID: "HCM_CAMPAIGN_MANAGER_UPLOAD_ID",
  HCM_CAMPAIGN_MANAGER_FORM_DATA: "HCM_CAMPAIGN_MANAGER_FORM_DATA",
  PROCEED_TO_PREVIEW: "PROCEED_TO_PREVIEW",
  ACTION_LABEL_RETRY: "ACTION_LABEL_RETRY",

  // ==========================================================================
  // 20. ADDITIONAL UTILITY KEYS
  // ==========================================================================
  TO_BE_UPDATED: "To Be Updated",
  T: "T",
  MR_DN: "MR-DN",
  ADD_COMMENT_OR: "ADD_COMMENT_(OR)",
  D: "D",

  // Campaign Card Navigation (Commented/Legacy)
  ACTION_TEST_APP_CONFIGURATION: "ACTION_TEST_APP_CONFIGURATION",
  ACTION_TEST_APP_CONFIGURATION_PARENT_MOBILE: "ACTION_TEST_APP_CONFIGURATION_PARENT_MOBILE",
  ACTION_TEST_APP_CONFIGURATION_PARENT_WEB: "ACTION_TEST_APP_CONFIGURATION_PARENT_WEB",
  ACTION_TEST_MY_CAMPAIGN: "ACTION_TEST_MY_CAMPAIGN",
  ACTION_TEST_SETUP_CAMPAIGN: "ACTION_TEST_SETUP_CAMPAIGN",

  // Campaign Summary & Requirements
  CAMPAIGN_REQUIREMENTS_HEADING: "CAMPAIGN_REQUIREMENTS_HEADING",
  CAMPAIGN_SUMMARY_ADD_ATTRIBUTES_ACTION: "CAMPAIGN_SUMMARY_ADD_ATTRIBUTES_ACTION",
  CAMPAIGN_SUMMARY_ADD_DATE_ACTION: "CAMPAIGN_SUMMARY_ADD_DATE_ACTION",
  CAMPAIGN_SUMMARY_ADD_DELIVERY_TYPE_ACTION: "CAMPAIGN_SUMMARY_ADD_DELIVERY_TYPE_ACTION",
  CAMPAIGN_SUMMARY_ADD_PRODUCT_ACTION: "CAMPAIGN_SUMMARY_ADD_PRODUCT_ACTION",
  CAMPAIGN_SUMMARY_ADD_VALUES_ACTION: "CAMPAIGN_SUMMARY_ADD_VALUES_ACTION",
  CAMPAIGN_SUMMARY_ATTRIBUTES_MISSING_ERROR: "CAMPAIGN_SUMMARY_ATTRIBUTES_MISSING_ERROR",
  CAMPAIGN_SUMMARY_DATE_MISSING_ERROR: "CAMPAIGN_SUMMARY_DATE_MISSING_ERROR",
  CAMPAIGN_SUMMARY_DELIVERY_TYPE_MISSING_ERROR: "CAMPAIGN_SUMMARY_DELIVERY_TYPE_MISSING_ERROR",
  CAMPAIGN_SUMMARY_PRODUCT_MISSING_ERROR: "CAMPAIGN_SUMMARY_PRODUCT_MISSING_ERROR",
  CAMPAIGN_SUMMARY_VALUES_MISSING_ERROR: "CAMPAIGN_SUMMARY_VALUES_MISSING_ERROR",
  HCM_CAMPAIGN_DETAILS_SUMMARY: "HCM_CAMPAIGN_DETAILS_SUMMARY",
  HCM_CAMPAIGN_FOR: "HCM_CAMPAIGN_FOR",
  HCM_CAMPAIGN_PROCEED: "HCM_CAMPAIGN_PROCEED",

  // Campaign Creation
  HCM_CREATE_CAMPAIGN_DESCRIPTION: "HCM_CREATE_CAMPAIGN_DESCRIPTION",
  HCM_CREATE_NEW_CAMPAIGN: "HCM_CREATE_NEW_CAMPAIGN",
  HCM_HOW_DO_YOU_WANT_TO_CREATE: "HCM_HOW_DO_YOU_WANT_TO_CREATE",
  HCM_IMPORT_EXISTING_CAMPAIGN: "HCM_IMPORT_EXISTING_CAMPAIGN",

  // Date Update & Info
  HCM_CAMPAIGN_DATE_MISSING: "HCM_CAMPAIGN_DATE_MISSING",
  HCM_CAMPAIGN_END_DATE_BEFORE_START_DATE: "HCM_CAMPAIGN_END_DATE_BEFORE_START_DATE",
  HCM_CAMPAIGN_END_DATE_EQUAL_START_DATE: "HCM_CAMPAIGN_END_DATE_EQUAL_START_DATE",
  HCM_UPDATE_DATE_INFO: "HCM_UPDATE_DATE_INFO",
  UPDATE_DATE_CHANGE_INFO_TEXT1: "UPDATE_DATE_CHANGE_INFO_TEXT1",
  UPDATE_DATE_CHANGE_INFO_TEXT2: "UPDATE_DATE_CHANGE_INFO_TEXT2",

  // Upload Data
  HCM_UPLOAD_DATA_DESC: "HCM_UPLOAD_DATA_DESC",
  HCM_UPLOAD_DATA_HEADING: "HCM_UPLOAD_DATA_HEADING",
  CAMPAIGN_UPLOADING_FILE: "CAMPAIGN_UPLOADING_FILE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  UPLOAD_GEOJSONS: "UPLOAD_GEOJSONS",

  // Product Modal
  CAMPAIGN_PRODUCTS_MODAL_SECONDARY_ACTION: "CAMPAIGN_PRODUCTS_MODAL_SECONDARY_ACTION",

  // Checklist
  ADD_NEW_CHECKLIST: "ADD_NEW_CHECKLIST",
  LINK_NESTED_CHECKLIST: "LINK_NESTED_CHECKLIST",
  SELECT_CHECKLIST_TYPE: "SELECT_CHECKLIST_TYPE",
  HCM_CHECKLIST_ROLE: "HCM_CHECKLIST_ROLE",

  // App Configuration Drawer
  CMP_DRAWER_WHAT_IS_FEATURE_APP_CONFIG_SCREEN: "CMP_DRAWER_WHAT_IS_FEATURE_APP_CONFIG_SCREEN",
  CMP_DRAWER_WHAT_IS_MODULE_APP_CONFIG_SCREEN: "CMP_DRAWER_WHAT_IS_MODULE_APP_CONFIG_SCREEN",
  LOADING_CONFIGURATION: "LOADING_CONFIGURATION",
  COPYING_CONFIG_FOR_SELECTED_MODULES: "COPYING_CONFIG_FOR_SELECTED_MODULES",
  SAVING_FEATURES_CONFIG_IN_SERVER: "SAVING_FEATURES_CONFIG_IN_SERVER",
  SELECT_ATLEAST_ONE_MODULE: "SELECT_ATLEAST_ONE_MODULE",
  HCM_MANDATORY_MODULES: "HCM_MANDATORY_MODULES",
  HCM_CHOOSE_FEATURE_FOR_APP: "HCM_CHOOSE_FEATURE_FOR_APP",
  ES_FEATURE_DISABLED: "ES_FEATURE_DISABLED",

  // Navigation Logic & Display Logic
  ADD_CONDITION: "ADD_CONDITION",
  ADD_DISPLAY_LOGIC: "ADD_DISPLAY_LOGIC",
  DISPLAY_LOGIC: "DISPLAY_LOGIC",
  HCM_ADD_RULE: "HCM_ADD_RULE",
  HCM_REMOVE_RULE: "HCM_REMOVE_RULE",
  HCM_NO_RULES_YET: "HCM_NO_RULES_YET",
  HCM_LOGIC: "HCM_LOGIC",
  HCM_JOIN_WITH: "HCM_JOIN_WITH",
  HCM_SELECT_FIELD: "HCM_SELECT_FIELD",
  HCM_SELECT_PAGE: "HCM_SELECT_PAGE",
  HCM_TARGET_PAGE: "HCM_TARGET_PAGE",
  HCM_SELECT_VALUE: "HCM_SELECT_VALUE",
  HCM_COMPARISION_TYPE: "HCM_COMPARISION_TYPE",
  HCM_IS_MAXIMUM_VALUE: "HCM_IS_MAXIMUM_VALUE",
  ENTER_VALUE: "ENTER_VALUE",
  ENTER_INTEGER_VALUE: "ENTER_INTEGER_VALUE",
  SELECT_FILTER: "SELECT_FILTER",
  INCOMPLETE_EXPRESSION: "INCOMPLETE_EXPRESSION",
  PLEASE_COMPLETE_ALL_CONDITIONS: "PLEASE_COMPLETE_ALL_CONDITIONS",
  REMOVE_CONDITION: "REMOVE_CONDITION",
  NO_LOGIC_ADDED: "NO_LOGIC_ADDED",
  ADD_COMMENT: "ADD_COMMENT",

  // Operators & Logic
  AND: "AND",
  OR: "OR",
  EQUALS_TO: "EQUALS_TO",
  NOT_EQUALS_TO: "NOT_EQUALS_TO",
  GREATER_THAN: "GREATER_THAN",
  GREATER_THAN_OR_EQUALS_TO: "GREATER_THAN_OR_EQUALS_TO",
  LESS_THAN: "LESS_THAN",
  LESS_THAN_OR_EQUALS_TO: "LESS_THAN_OR_EQUALS_TO",
  DESELECT: "DESELECT",

  // MDMS & Localization Errors
  HCM_MDMS_DATA_UPDATE_ERROR: "HCM_MDMS_DATA_UPDATE_ERROR",
  HCM_MDMS_DATA_UPSERT_ERROR: "HCM_MDMS_DATA_UPSERT_ERROR",
  LOCALISATION_ERROR: "LOCALISATION_ERROR",
  LOCALISATION_FETCH_ERROR: "LOCALISATION_FETCH_ERROR",

  // Success Responses (Additional)
  ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE_TEXTKK: "ES_CAMPAIGN_CREATE_SUCCESS_RESPONSE_TEXTKK",
  ES_CAMPAIGN_SUCCESS_INFO_TEXTKK: "ES_CAMPAIGN_SUCCESS_INFO_TEXTKK",
  ES_CAMPAIGN_SELECT: "ES_CAMPAIGN_SELECT",
  WBH_HIERARCHY_CREATED: "WBH_HIERARCHY_CREATED",

  // Cache & Wait Messages
  SURE_TO_CLEAR_CACHE: "SURE_TO_CLEAR_CACHE",
  SURE_TO_CLEAR_CACHE_MODAL_TEXT: "SURE_TO_CLEAR_CACHE_MODAL_TEXT",
  PLEASE_WAIT_AND_RETRY_AFTER_SOME_TIME: "PLEASE_WAIT_AND_RETRY_AFTER_SOME_TIME",

  // Authorization & Links
  USER_NOT_AUTHORISED: "USER_NOT_AUTHORISED",
  CUSTOM_REPORTS_LINK: "CUSTOM_REPORTS_LINK",
  FEEDBACK_LINK: "FEEDBACK_LINK",

  // Placeholder for examples in README
  YOUR_CONSTANT: "YOUR_CONSTANT",
};
