const data={
    "responseInfo": {
        "apiId": "org.egov.accesscontrol",
        "ver": null,
        "ts": 1723182672458,
        "resMsgId": "uief87324",
        "msgId": "1723182672458|en_IN",
        "status": "200 OK"
    },
    "modules": null,
    "actions": [
        {
            "id": 1,
            "name": "Home",
            "url": "url",
            "displayName": "Home",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "works",
            "enabled": true,
            "serviceCode": "works",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "0Home",
            "navigationURL": "/works-ui/employee/",
            "leftIcon": "dynamic:MuktaHomeIcon",
            "rightIcon": ""
        },
        {
            "id": 5,
            "name": "HRMS",
            "url": "url",
            "displayName": "Search Employee",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "HRMS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "9HRMS.Search",
            "navigationURL": "/works-ui/employee/hrms/inbox",
            "leftIcon": "dynamic:HRIcon",
            "rightIcon": ""
        },
        {
            "id": 13,
            "name": "HRMS",
            "url": "url",
            "displayName": "Create Employee",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "HRMS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "9HRMS.Create",
            "navigationURL": "/works-ui/employee/hrms/create",
            "leftIcon": "dynamic:HRIcon",
            "rightIcon": ""
        },
        {
            "id": 14,
            "name": "ESTIMATE",
            "url": "url",
            "displayName": "Create Estimate",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "WORKS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "2ESTIMATE.CreateEstimate",
            "navigationURL": "/works-ui/employee/project/search-project",
            "leftIcon": "dynamic:EstimateIcon",
            "rightIcon": ""
        },
        {
            "id": 15,
            "name": "PROJECT",
            "url": "url",
            "displayName": "Create Project",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "PROJECT",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "1PROJECT.Create",
            "navigationURL": "/works-ui/employee/project/create-project",
            "leftIcon": "dynamic:ProjectIcon",
            "rightIcon": ""
        },
        {
            "id": 16,
            "name": "ESTIMATE",
            "url": "url",
            "displayName": "Search Estimate",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "ESTIMATE",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "2ESTIMATE.SearchEstimate",
            "navigationURL": "/works-ui/employee/estimate/search-estimate",
            "leftIcon": "dynamic:EstimateIcon",
            "rightIcon": ""
        },
        {
            "id": 17,
            "name": "ESTIMATE",
            "url": "url",
            "displayName": "Estimate Inbox",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "ESTIMATE",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "2ESTIMATE.EstimateInbox",
            "navigationURL": "/works-ui/employee/estimate/inbox",
            "leftIcon": "dynamic:EstimateIcon",
            "rightIcon": ""
        },
        {
            "id": 18,
            "name": "PROJECT",
            "url": "url",
            "displayName": "PROJECT Search",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "PROJECT",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "1PROJECT.search",
            "navigationURL": "/works-ui/employee/project/search-project",
            "leftIcon": "dynamic:ProjectIcon",
            "rightIcon": ""
        },
        {
            "id": 54,
            "name": "BILLS",
            "url": "url",
            "displayName": "Bill Inbox",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "BILLS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "5BILLS.BillInbox",
            "navigationURL": "/works-ui/employee/expenditure/billinbox",
            "leftIcon": "dynamic:ExpenditureIcon",
            "rightIcon": ""
        },
        {
            "id": 55,
            "name": "BILLS",
            "url": "url",
            "displayName": "Create Purchase Bill",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "BILLS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "5BILLS.CreatePurchaseBill",
            "navigationURL": "/works-ui/employee/contracts/search-contract?status=ACCEPTED",
            "leftIcon": "dynamic:ExpenditureIcon",
            "rightIcon": ""
        },
        {
            "id": 56,
            "name": "BILLS",
            "url": "url",
            "displayName": "Bill Search",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "BILLS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "BILLS.BillSearch",
            "navigationURL": "/works-ui/employee/expenditure/search-bill",
            "leftIcon": "dynamic:ExpenditureIcon",
            "rightIcon": ""
        },
        {
            "id": 57,
            "name": "BILLS",
            "url": "url",
            "displayName": "Bill View",
            "orderNumber": 4,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "BILLS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "5BILLS.BillView",
            "navigationURL": "/works-ui/employee/expenditure/view-bills/menu",
            "leftIcon": "dynamic:ExpenditureIcon",
            "rightIcon": ""
        },
        {
            "id": 58,
            "name": "CONTRACTS",
            "url": "url",
            "displayName": "Contracts Inbox",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "CONTRACTS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "3CONTRACTS.Inbox",
            "navigationURL": "/works-ui/employee/contracts/inbox",
            "leftIcon": "dynamic:ContractIcon",
            "rightIcon": ""
        },
        {
            "id": 59,
            "name": "ATTENDENCEMGMT",
            "url": "url",
            "displayName": "ATTENDENCEMGMT Inbox",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "ATTENDENCEMGMT",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "4ATTENDENCEMGMT.Inbox",
            "navigationURL": "/works-ui/employee/attendencemgmt/inbox",
            "leftIcon": "dynamic:AttendanceIcon",
            "rightIcon": ""
        },
        {
            "id": 60,
            "name": "CONTRACTS",
            "url": "url",
            "displayName": "Contracts Create",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "CONTRACTS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "3CONTRACTS.Create",
            "navigationURL": "/works-ui/employee/estimate/search-estimate?status=APPROVED",
            "leftIcon": "dynamic:ContractIcon",
            "rightIcon": ""
        },
        {
            "id": 61,
            "name": "CONTRACTS",
            "url": "url",
            "displayName": "Contracts Search",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "CONTRACTS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "3CONTRACTS.Search",
            "navigationURL": "/works-ui/employee/contracts/search-contract",
            "leftIcon": "dynamic:ContractIcon",
            "rightIcon": ""
        },
        {
            "id": 62,
            "name": "CHECKLIST",
            "url": "url",
            "displayName": "CHECKLIST Inbox",
            "orderNumber": 3,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "CHECKLIST",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "CHECKLIST.Inbox",
            "navigationURL": "/works-ui/employee/works/checklistinbox",
            "leftIcon": "dynamic:HRIcon",
            "rightIcon": ""
        },
        {
            "id": 63,
            "name": "CHECKLIST",
            "url": "url",
            "displayName": "CHECKLIST Create",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "CHECKLIST",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "CHECKLIST.Create",
            "navigationURL": "/works-ui/employee/works/checklist",
            "leftIcon": "dynamic:HRIcon",
            "rightIcon": ""
        },
        {
            "id": 62,
            "name": "MASTERS",
            "url": "url",
            "displayName": "Masters Search Organisation",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "MASTERS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "7MASTERS.Search",
            "navigationURL": "/works-ui/employee/masters/search-organization",
            "leftIcon": "dynamic:OrganisationIcon",
            "rightIcon": ""
        },
        {
            "id": 63,
            "name": "WAGESEEKER",
            "url": "url",
            "displayName": "Masters Create WageSeeker",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "WageSeeker",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "8WageSeeker.CreateWageSeeker",
            "navigationURL": "/works-ui/employee/masters/create-wageseeker",
            "leftIcon": "dynamic:WageseekerIcon",
            "rightIcon": ""
        },
        {
            "id": 64,
            "name": "MASTERS",
            "url": "url",
            "displayName": "Masters Create Organisation",
            "orderNumber": 2,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "MASTERS",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "7MASTERS.CreateOrganisation",
            "navigationURL": "/works-ui/employee/masters/create-organization",
            "leftIcon": "dynamic:OrganisationIcon",
            "rightIcon": ""
        },
        {
            "id": 78,
            "name": "WAGESEEKER",
            "url": "url",
            "displayName": "Masters Search Wageseeker",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "WageSeeker",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "8WageSeeker.Search",
            "navigationURL": "/works-ui/employee/masters/search-wageseeker",
            "leftIcon": "dynamic:WageseekerIcon",
            "rightIcon": ""
        },
        {
            "id": 90,
            "name": "ATTENDENCEMGMT",
            "url": "url",
            "displayName": "ATTENDENCEMGMT Search",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "ATTENDENCEMGMT",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "4ATTENDENCEMGMT.Search",
            "navigationURL": "/works-ui/employee/attendencemgmt/search-attendance",
            "leftIcon": "dynamic:AttendanceIcon",
            "rightIcon": ""
        },
        {
            "id": 2024,
            "name": "UtilizationStatement",
            "url": "/statements/v1/utilization/_create",
            "displayName": "Utilization Statement",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "statements",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "",
            "navigationURL": "",
            "leftIcon": "",
            "rightIcon": ""
        },
        {
            "id": 2027,
            "name": "UtilizationStatementSearch",
            "url": "/statements/v1/utilization/_search",
            "displayName": "Utilization Statement",
            "orderNumber": 1,
            "queryParams": "",
            "parentModule": "",
            "enabled": true,
            "serviceCode": "statements",
            "tenantId": "pg",
            "createdDate": null,
            "createdBy": null,
            "lastModifiedDate": null,
            "lastModifiedBy": null,
            "path": "",
            "navigationURL": "",
            "leftIcon": "",
            "rightIcon": ""
        }
    ]
};
export default data;