name: Digit Admin Console Build workflow
on:
  push:
    branches: [ 'develop','console-arm','master']
    paths:
      - 'micro-ui/web/micro-ui-internals/**'
  workflow_dispatch:

jobs:
  docker_image-build:
    outputs:
      run_job_digit_ui: ${{ steps.check_files.outputs.run_job_digit_ui }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          run_job_digit_ui=false
          while IFS= read -r file
          do
            if [[ $file == micro-ui/* ]]; then
              echo "This modified file is under the 'digit_ui' folder."
              run_job_digit_ui=true
            fi
          done < files.txt

          echo "::set-output name=run_job_digit_ui::$run_job_digit_ui"
          echo "ACTION_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA: -8}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Login to egovio docker Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker image for core-ui
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          IMAGE_NAME=core-ui:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ env.ACTION_NUMBER }}
          docker build -t $IMAGE_NAME -f web/core/Dockerfile .
          docker tag $IMAGE_NAME egovio/$IMAGE_NAME
          docker push egovio/$IMAGE_NAME

          echo "IMAGE_NAME=egovio/$IMAGE_NAME" >> $GITHUB_ENV
        working-directory: micro-ui

      - name: Display Docker image in Actions tab
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          echo "Built Docker image: ${{ env.IMAGE_NAME }}"
          echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Show Docker image in job summary
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          echo "## Docker image built and pushed:" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
