name: Digit Admin Console Build workflow
on:
  push:
    branches: [ 'develop', 'multiarch-console-stable-arm', 'master' ]
    paths:
      - 'health/micro-ui/web/micro-ui-internals/**'
  workflow_dispatch:

jobs:
  docker_image-build:
    outputs:
      run_job_digit_ui: ${{ steps.check_files.outputs.run_job_digit_ui }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          run_job_digit_ui=false
          while IFS= read -r file; do
            if [[ $file == health/micro-ui/* ]]; then
              echo "This modified file is under the 'digit_ui' folder."
              run_job_digit_ui=true
            fi
          done < files.txt
          echo "::set-output name=run_job_digit_ui::$run_job_digit_ui"
          echo "ACTION_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA: -8}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Login to egovio Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push multi-arch image
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          TAG=${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ env.ACTION_NUMBER }}
          IMAGE=egovio/core-ui:$TAG
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f health/micro-ui/web/core/Dockerfile \
            -t $IMAGE \
            --push \
            health/micro-ui
          echo "IMAGE_NAME_2=$IMAGE" >> $GITHUB_ENV

      - name: Display Docker image
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          echo "Docker image published: ${{ env.IMAGE_NAME_2 }}"
          echo "::set-output name=second_image::${{ env.IMAGE_NAME_2 }}"

      - name: Show Docker images in job summary
        if: ${{ steps.check_files.outputs.run_job_digit_ui == 'true' }}
        run: |
          echo "## Docker images built and pushed:" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ env.IMAGE_NAME_2 }}" >> $GITHUB_STEP_SUMMARY
